### ISSUE TITLE
`dirivish-toggle-subtree` Gives error: "Not a directory" [Bug] 

### ISSUE THREAD

**Issue by tdstoff** [alexluigit/dirvish#106]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [x] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

My config gives the error "Not a directory" when I run `dirvish-toggle-subtree` (TAB) on lines that are clearly directories in a dirvish buffer, and thus doesn't expand into a subtree. 

### Steps to reproduce

I think this is a clash with either one of the Doom modules I have installed or another package I import, as running the vanilla Doom config doesn't reproduce the issue. I attach my init.el (Doom modules) and packages.el (other packages) which produces the issue for me if I just put the Dirvish sample config in config.el.

Looking for any suggestions on how to debug this, as `dirvish-toggle-subtree` works wonderfully from what I've seen. I've tried disabling basically every minor mode I could in the Dirvish buffer to no avail. Tried this running both Emacs 28 and 29. I see where the error gets called in dirvish-subtree.el, but don't understand exactly how the directory paths are processed there.

[packages.el.txt](https://github.com/alexluigit/dirvish/files/9182250/packages.el.txt)
[init.el.txt](https://github.com/alexluigit/dirvish/files/9182252/init.el.txt)

### Expected behavior

`dirvish-toggle-subtree` Should neatly expand or collapse directories.

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

Doom Emacs

### Error callstack

```emacs-lisp
I tried this, and the user-error call for some reason doesn't send me into debug mode.
```

### Anything else

I've noticed too that `diff-hl-dired` is not integrating properly with the `git-msg` extension, as they both show in the margin at once. Perhaps these issues are related, as this issue has the same persistence.

![image](https://user-images.githubusercontent.com/43076118/180808058-6cd50823-4871-4d22-89da-8e7ccc9ba64e.png)
![image](https://user-images.githubusercontent.com/43076118/180808387-ed64d97f-ce91-414f-ad47-8bbf9aca4d5b.png)

**Comment by alexluigit** [comment]
Go to the dirvish buffer that you can reproduce the error with the `dired-hide-details-mode` turned **off** (shift + 9), what is the first character of that line (more specifically the first char in the priv column)?

**Comment by tdstoff** [comment]
Okay, I see that about `diff-hl-dired-mode` now, thanks.

The error still persist with `dired-hide-details-mode` off. The first character you're referring to I think is the 'd'?

![image](https://user-images.githubusercontent.com/43076118/180817536-a39a12a0-62aa-4581-9503-faeb45a1987a.png)

**Comment by alexluigit** [comment]
What's the output of `ls --version` on terminal?

**Comment by alexluigit** [comment]
Do you have `--size` flag in your `dired-listing-switches`? Would remove it work?

**Comment by tdstoff** [comment]
The `--version` command [isn't supported](https://unix.stackexchange.com/questions/207136/why-does-my-ls-help-not-work) on my MacOS `ls`. Actually, no long-formatted arguments are supported except for `--size` is what it looks like. Maybe this is the root of my problem?

The listing switches I currently have are `"-alFtshr"`.

**Comment by tdstoff** [comment]
Setting the listing switches to the basic `"-al"` doesn't do it either.

**Comment by alexluigit** [comment]
Install gnu ls first. And follow the instructions in this [section](https://github.com/alexluigit/dirvish/blob/main/CUSTOMIZING.org#parsing-switches)
```shell
brew install coreutils
```

**Comment by tdstoff** [comment]
Okay, running GNU coreutils now. Made sure it's on shell $PATH as well as exec-path. I can run with all the ls switches like on that page. The error actually still persists. For some reason the directory icons are blank now, don't know if that has to do with anything.

![image](https://user-images.githubusercontent.com/43076118/180823853-b0389135-fbb4-4a0e-aae2-7ca17eb32d31.png)

**Comment by tdstoff** [comment]
Oh okay, "drwx..." is actually still not the first column. I see that's not conventional now. 

![image](https://user-images.githubusercontent.com/43076118/180824256-0fe90a12-0761-46af-8ffa-07db71277224.png)

**Comment by alexluigit** [comment]
Remove the "--size" (or "-s") flag in your dired-listing-switches.

**Comment by tdstoff** [comment]
Yes, that did it. Thank you!
