### ISSUE TITLE
[Bug] dirvish and undo-tree

### ISSUE THREAD

**Issue by cgrabenstein** [alexluigit/dirvish#107]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Deleting a `.~undo-tree~` file generates a new `.~undo-tree~.~undo-tree~` file.

### Steps to reproduce

1. `M-x dirvish` in a folder that contains undo-tree files
2. delete one of the undo-tree files

Expected: the file is deleted and no new undo-tree file is created
Actual: a new undo-tree file is created

### Expected behavior

See above

### OS

MacOS

### Emacs Version

28

### Anything else

I'm not sure if it's technically a bug, or just some miss-configuration? Feel free to close this if there's some easy solution that I am missing.

**Comment by alexluigit** [comment]
Let me know if the latest commit works.

**Comment by cgrabenstein** [comment]
Unfortunately not, it's still the same behavior.

**Comment by alexluigit** [comment]
I believe 69738a8467e748b8d3c7de9f607f796d6c725704 fixed this. Feel free to reopen if it failed to do so.
