### ISSUE TITLE
Nested directory listings do not respect configured ls flags

### ISSUE THREAD

**Issue by jdtsmith** [alexluigit/dirvish#108]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Using `? l a` to set the listing switches for all files works well, both for the current directory and any sub-directory you enter (with Ret).  But expanding a directory (with Tab) does not apply the same flags to the expanded subdirectory.

### Steps to reproduce

- remove `--all` from the directory listing: notice dotfiles vanish.
- Use Tab to open a directory with dot files: dot files in the expanded subdirectory remain.

### Expected behavior

Listing flags are applied uniformly to files in the current directory and any expanded subdirectories. 

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

NA

### Anything else

Thanks for dirvish, really wonderful tool.

**Comment by alexluigit** [comment]
Thanks for the report!
