### ISSUE TITLE
Doesn't work fine with winner-mode

### ISSUE THREAD

**Issue by Joxos** [alexluigit/dirvish#11]
I've found that if you execute `winner-undo` after `dirvish`, you'll probably get:
![image](https://user-images.githubusercontent.com/37507136/153789393-03bc392a-ae9a-407e-8d7c-cd453237f758.png)
How can I solve it?

**Comment by alexluigit** [comment]
Please try out a51cf33293abbb2a72003ca1e43e2419fa9dc526 and see if this have been fixed.

**Comment by Joxos** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Joxos** [comment]
![image](https://user-images.githubusercontent.com/37507136/153822799-258854d7-e837-4ac4-9616-dceb75d94e75.png)
I've updated to the latest version but this still happens to me.

**Comment by Joxos** [comment]
BTW, I restarted the emacs after `git pull`.

**Comment by Joxos** [comment]
Nope, I've tried that.

**Comment by alexluigit** [comment]
Hope 78d30d7d3137cdf70a9849f135716376de1b73a9 solved this issue for you.

**Comment by Joxos** [comment]
![image](https://user-images.githubusercontent.com/37507136/153972219-49f89f6d-a75b-4db7-9f38-811e92f3d981.png)
Nope, the problem still exists.
![image](https://user-images.githubusercontent.com/37507136/153972309-815072e4-4c97-4805-be4a-502894f76dcb.png)

**Comment by alexluigit** [comment]
Can you provide a minimal setup to reproduce this? 
I've tested with following setups (on Emacs 29) and it works fine. 
```emacs-lisp
emacs -q -L . -l dirvish.el --eval '(progn (winner-mode 1) (dirvish))'
;; or
emacs -q -L . -l dirvish.el --eval '(progn (winner-mode 1) (dirvish) (quit-window))'
;; then M-x winner-undo
```

**Comment by fleimgruber** [comment]
I can't reproduce this with latest dirvish, assuming the repro steps are

1. M-x dirvish
2. M-x winner-undo
