### ISSUE TITLE
Add `magit-dired-log` to transient menu?

### ISSUE THREAD

**Issue by jdtsmith** [alexluigit/dirvish#111]
**Describe the solution you'd like**
If magit is loaded, add magit-dired-log command to `?` transient (perhaps on `L`).

**Describe alternatives you've considered**
Easy to do yourself, but having `?` is such a convenience!

**Comment by alexluigit** [comment]
Thanks for the advice.

See: https://github.com/alexluigit/dirvish/blob/main/docs/EXTENSIONS.org#version-control-git-integration-dirvish-vcel

Pressing `? vv` gives you the log for both files and dirs. No magit needed.  Maybe consider bind `v` to `dirvish-vc-menu` in `dirvish-mode` if you think it's handy.  Further more, `M-x other-window` brings you to the preview window, you can then use commands in `vc-git-log-view-mode-map`, `=` for diff, `f` for find revision, etc.

**Comment by alexluigit** [comment]
The option only shows up in fullframe sessions. I've amended the commit, now it should appear in single window session too.

**Comment by jdtsmith** [comment]
Thanks, this works.  One nice feature of magit-dired-log is you can mark multiple files, then log them all together, compactly.  I may just bind that to `? v l` or similar.

**Comment by alexluigit** [comment]
I believe you can achieve the same thing by setting `vc-log-short-style` to '(directory file)
