### ISSUE TITLE
[Bug] Can't open a text file ending in .mod

### ISSUE THREAD

**Issue by chee** [alexluigit/dirvish#114]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When i try to open a `go.mod` file, instead emacs does nothing. It prints no error.

I've traced this down to this line:

https://github.com/alexluigit/dirvish/blob/db0f2890ebed1bab40c687a56efe26c4d3e81b4c/dirvish.el#L168

the audio extensions here contain `mod`. It tries to open it in `mpv`, i guess. which doesn't work! because in this case it is not a banging fasttracker mod file, it's a plain text file!!1

(i tried removing `mod` from that list and then i am able to listen to code)

### Steps to reproduce

try to open a .mod file in dirvish or even with C-x C-f!

### Expected behavior

i'd like if it opened it, but also it would be nice if it printed an error message. it might also be good to ask me the first time i try to open a binary file "what would you like to do here?"

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

https://chee.baby/notebook/docfiles/emacs/init.html

### Error callstack

```emacs-lisp
none! prints no errors!
```

### Anything else

no screenshots or logs!!!

**Comment by chee** [comment]
for now i'm customizing `dirvish-open-with-programs` to `nil` which works for me for now:)

**Comment by alexluigit** [comment]
Thanks for your report!
