### ISSUE TITLE
[Bug] `file-size` in `dirvish-attributes` makes lines wrap around in TTY sessions

### ISSUE THREAD

**Issue by tsdh** [alexluigit/dirvish#115]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I have `file-size` in my `dirvish-attributes` which works fine in sessions with a graphical frame but it seems there's something wrong with the column calculation in TTY frames where the last character of the file size is one column too far at the right and thus wraps around in the next line.  Here's a screenshot showing the issue.

![Screenshot-2022-08-05_070203](https://user-images.githubusercontent.com/103854/183005233-72ae7e5b-af90-4b6e-af96-6653a23f1162.png)

A possible candidate for that issue might be that dirvish assumes there are 1-column fringes which aren't there in TTY sessions.  If that's the case, using the function `fringe-columns` in such calculations would be the right thing as they can also be customized (or disabled) in frame sessions.

EDIT: No, it doesn't seem like a fringe problem.  I cannot reproduce the issue in a graphical frame after `(setopt fringe-mode 0)` which disables fringes.

### Steps to reproduce

I can reproduce that behavior with at least the current emacs master branch starting with `emacs -Q` and then evaluating the following code in `*scratch*`:

```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/dirvish-20220804.1521")
(require 'dirvish)
(dirvish-override-dired-mode)
(setopt dirvish-attributes '(vc-state subtree-state collapse file-size))
```

### Expected behavior

The file size does not make lines wrap around like in graphical sessions.

### OS

Linux

### Emacs Version

29

### Emacs Configurations

vanilla

**Comment by alexluigit** [comment]
Did 884abea fixed this?

**Comment by tsdh** [comment]
Yes, but now it looks like I have 2 free columns right of the file size in a TTY frame where it was and still is just one column in a graphical frame.

TTY: ![image](https://user-images.githubusercontent.com/103854/183041729-53956015-1074-4287-ac94-0cc2e8b0b108.png)
Graphical: ![image](https://user-images.githubusercontent.com/103854/183042101-218226c0-fa40-457d-8dd9-6571885ff1d6.png)

**Comment by alexluigit** [comment]
https://github.com/alexluigit/dirvish/commit/f2c54335e637699c4afdb2fb630508521fdbdf49 ?

**Comment by tsdh** [comment]
Kind of.  It works both in GUI as in TTY but not when I start a GUI emacs with a server and then connect to it via `emacsclient -t`.  That's nothing you can test once and be done but you probably need to always check `(window-system)` which returns `non-nil` on any graphical window system and `nil` on terminals.

**Comment by alexluigit** [comment]
I see. I guess 95973cf2d045735d583b4cc6f9bb7432f0626db6 should cut it. Thanks for your feedback.

**Comment by tsdh** [comment]
Yes, that works fine now.  Thanks a lot!
