### ISSUE TITLE
[Feature Request] Fix `dirvish` recipe for `straight.el` in the README.

### ISSUE THREAD

**Issue by eppolito** [alexluigit/dirvish#116]
**Problem**: `straight.el` recipe from the docs does not seem to work (I get a weird `*straight-process*` error about the repo not existing).

**Proposed solution**: Update the docs.  The following recipe does work for me:
`(straight-use-package '(dirvish :type git :repo "alexluigit/dirvish" :host github))`.
I can make a pull request if necessary.

**Alternatives**: Figure out why `straight.el` does not register `dirvish` from `melpa`.  I had no luck with this after a few hours, but I'm probably missing something.  I started a [discussion](https://github.com/radian-software/straight.el/discussions/984) on the `straight.el` repo.

**Comment by alexluigit** [comment]
The recipe in the README works fine. Perhaps you should follow the instructions @progfolio posted in the discussion.
