### ISSUE TITLE
[Bug] `:right` in dirvish header line falls off

### ISSUE THREAD

**Issue by jdtsmith** [alexluigit/dirvish#117]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Setting `dirvish-header-line-format` to `'(:left (path) :right (vc-info))` results in the branch name falling slightly off the frame:

![image](https://user-images.githubusercontent.com/93749/183148001-64a47858-27cd-4e5c-8498-6954fab927db.png)

I can add a space after `(vc-info)` and it works fine. 

### Steps to reproduce

see above

### Expected behavior

Right-aligned vc-info.

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

self-customized

**Comment by alexluigit** [comment]
Can you reproduce this with `emacs -Q`? Perhaps it has something to do with the theme or font setup. Did the falling off happened with all file names (under the cursor)?  I'm not able to reproduce this with both 28/29.

**Comment by jdtsmith** [comment]
You are right, it's not reproduced in `emacs -Q`.  The issue seems likely to be the font size of the path name at left in the header (emacs -Q on top):

![image](https://user-images.githubusercontent.com/93749/183251051-21bb1532-5f7e-4136-86a5-e84413d0f09c.png)

What face is used for the path display?

**Comment by alexluigit** [comment]
It's `dired-header` for "~" and "setup.py" part in the pic.

**Comment by jdtsmith** [comment]
Thanks.  I noticed my theme ([alect-themes](https://github.com/alezost/alect-themes)) sets the height to 1.13 for dired-header.  Also whatever face the blue path name has had a different height increase.  I fixed both by setting `alect-header-height=1.0` before loading the theme; with that, alignment is just as in emacs -Q. 

But I wonder how common changing header heights or fonts is in various themes/setups?  Right alignment by spaces via display properties really breaks down in the face of multiple heights/fonts per line. But `:align-to` via pixel offset requires computing the pixel width of the thing being aligned, e.g. with `window-text-pixel-size`.  It's possible to use a temp buffer in the current window, insert the right-aligned fully propertized string, measure its pixel width, then calculate the precise `:align-to` pixel offset.  Probably not terribly expensive in the face of all the vc computation maybe going on behind the scenes.

**Comment by alexluigit** [comment]
> It's possible to use a temp buffer in the current window, insert the right-aligned fully propertized string, measure its pixel width, then calculate the precise :align-to pixel offset. 

Not sure, but looks like a good idea, I'll give it a try and see if it has bad implication on performance.

> Probably not terribly expensive in the face of all the vc computation maybe going on behind the scenes.

The directory data (file attributes, vc state, etc.) retrieving process is async and only being executed once, but the mode line refreshment is called on every redisplay, so still have to handle it with caution.

**Comment by jdtsmith** [comment]
I know minad has looked at it for marginalia, which would need to align many dozens of bits of text in a responsive manner, and it was pretty slow.  But for just a single right-aligned mode line sub-string, I bet it will be OK.  [Here's](https://www.reddit.com/r/emacs/comments/dht2wn/get_pixel_width_of_text_in_variablewidth_font_for/) a useful thread.   

> mode line refreshment is called on every redisplay 

Ah, right.  Assuming the format is fixed, it might be sensible to cache the pixel size computation and only recompute it when new information appears.   In the meantime I'll close this as fixed.
