### ISSUE TITLE
[Bug] `winconf-change` called on transient-popup

### ISSUE THREAD

**Issue by jdtsmith** [alexluigit/dirvish#118]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

`dirvish-winconf-change-h` is called 6 times upon popping up the transient menu with `?`.  On the first call, this unnecessarily recomputes the vc fringe color and git message.  

### Steps to reproduce

1. Enable `vc-state` and `git-msg` attributes. 
2. Summon the transient menu with `?`
3. Notice state disappears, then reappears after delay. 

### Expected behavior

Invoking the transient menu does not invalidate unchanged state. 

### OS

MacOS

### Emacs Version

28

**Comment by alexluigit** [comment]
The `dirvish-winconf-change-h` only get called 2 times on my end when pressing `?`, and I did not observed the redisplay of vc-state you mentioned.  `emacs -Q`? What's your setup for transient.el?

**Comment by jdtsmith** [comment]
OK I better start testing; not there with emacs -Q, and I confirm it's only called twice.  I located the issue: it's with [moody](https://github.com/tarsius/moody), a mode line mode by tarsius (author of transient).  The call stack of the first of 6 calls to winconf-change-h looks like:

```elisp
1 -> (dirvish-winconf-change-h)  backtrace-to-string(nil)
  (closure (t) nil (backtrace-to-string (backtrace-get-frames 'backtrace)))()
  #f(compiled-function (body &rest args) #<bytecode 0xcd8a00d7237b82>)(#<subr dirvish-winconf-change-h>)
  apply(#f(compiled-function (body &rest args) #<bytecode 0xcd8a00d7237b82>) #<subr dirvish-winconf-change-h> nil)
  dirvish-winconf-change-h()
  redisplay_internal\ \(C\ function\)()
  moody-redisplay(#<window 9> nil below nil)
  apply(moody-redisplay (#<window 9> nil below nil))
  split-window(#<window 9> nil below nil)
  split-window-no-error(#<window 9> nil below)
  window--make-major-side-window(#<buffer  *transient*> bottom 0 ((side . bottom) (dedicated . t) (inhibit-same-window . t) (window-parameters (no-other-window . t))))
  display-buffer-in-side-window(#<buffer  *transient*> ((side . bottom) (dedicated . t) (inhibit-same-window . t) (window-parameters (no-other-window . t))))
  display-buffer(#<buffer  *transient*> (display-buffer-in-side-window (side . bottom) (dedicated . t) (inhibit-same-window . t) (window-parameters (no-other-window . t))))
  transient--show()
  transient--redisplay()
  transient-setup(dirvish-dispatch)
  dirvish-dispatch()
  funcall-interactively(dirvish-dispatch)
  command-execute(dirvish-dispatch)
```


A potential fix is let-disabling during the popup:

```elisp
  (let ((window-configuration-change-hook nil))
    (if dirvish--props (transient-setup 'dirvish-dispatch)
      (user-error "Not in a Dirvish buffer"))))
```

**Comment by alexluigit** [comment]
The root cause is this: https://github.com/tarsius/moody/blob/master/moody.el#L487
Looks like a hack for Emacs 29-
