### ISSUE TITLE
[Feature Request] Option for full buffer navigation

### ISSUE THREAD

**Issue by karthink** [alexluigit/dirvish#119]
**Is your feature request related to a problem? Please describe.**
I often use the cursor in dired to select and copy rectangles, parts of file names etc. `dirvish-setup` sets the `cursor-type` to `nil` and I can't do this anymore. (I have to switch to `wdired-mode` to be able to do this.) I tried to re-show the cursor manually using a helper in `dirvish-mode-hook`, but just showing the cursor doesn't help since _horizontal cursor movement (`forward-char` etc) is also disabled by dirvish_.

**Describe the solution you'd like**
- Make cursor hiding in dirvish optional by adding a `dirvish-hide-cursor` variable, perhaps. (The default behavior stays the same.)
- Allow full/free buffer navigation when this option is set.

**Describe alternatives you've considered**
N/A

**Additional context**
Dirvish's default behavior breaks an implicit paradigm of Emacs: **Everything is a buffer with the same affordances.**.  So while special buffers are read-only, and many buffer modes (like dired) bind additional commands to keys, the default navigation and selection options are never taken away from the user. This baseline of consistency usually implies that new means of navigation (Avy etc) also generally work the same across Emacs.

(One big exception to this rule used to be Transient -- transient popups were not navigable. This has now been remedied with a user option.)

Please let me know if I missed an existing option.

**Comment by alexluigit** [comment]
Done. Thanks for the advice.

**Comment by karthink** [comment]
Just tested it out, it works great! Thank you for Dirvish, it's fantastic.
