### ISSUE TITLE
Guidance on configuring dirvish-open-with-programs

### ISSUE THREAD

**Issue by jmburgos** [alexluigit/dirvish#121]
Hi Alex,

Thank you for Dirvish.  It is great! After many years of using emacs and trying hard to like Dired, I am finally doing all my file manipulations in Emacs.

I am having a small issue.  I cannot configure `dirvish-open-with-programs`.  If I evaluate the following code in an lisp buffer, then Dirvish does what I want, for example opening word files with Libre Office: 

```
(defconst dirvish-libre-exts '("doc" "docx" "odt" "ods" "xls" "rtf" "xlsx" "odp" "ppt" "pptx"))

  (defcustom dirvish-open-with-programs
    `((,dirvish-audio-exts . ("mpv" "%f"))
      (,dirvish-video-exts . ("mpv" "%f"))
      (,dirvish-libre-exts . ("libreoffice" "%f"))
      (("html") . ("qutebrowser" "%f"))
      )
    "Association list of mimetype and external program for `find-file'.
Each element is of the form (EXTS . (CMD . ARGS)).  EXTS is a
list of file name extensions.  Once the EXTS is matched with
FILENAME in `find-file', a subprocess according to CMD and its
ARGS is issued to open the file outside of Emacs.  The special
placeholder \"%f\" in the ARGS is replaced by the FILENAME at
runtime.  Set it to nil disables this feature."
    :group 'dirvish
    :type '(alist :key-type ((repeat string) :tag "File mimetype or extensions")
                  :value-type ((repeat string) :tag "External command and args")))
  )
```

But if I put the same code in the ":config" section of my use-package declaration, the value of `dirvish-open-with-programs` is not updated, and the word document is open in Doc view.  I am not sure what I am doing wrong.

Could you clarify how to configure `dirvish-open-with-programs`? Perhaps you could add an example in your sample configuration here: 

https://github.com/alexluigit/dirvish/blob/main/docs/CUSTOMIZING.org#sample-config

Many thanks!

**Comment by alexluigit** [comment]
Hi,
> put the same code in the ":config" section 

Did you mean you put the `defcustom` declaration in the config section?  Does `setq` work for this variable?

**Comment by jmburgos** [comment]
This is embarassing... I should have started with the obvious.  With this in my :config section everything works fine. Thank you again. :)

```
(setq dirvish-libre-exts '("doc" "docx" "odt" "ods" "xls" "rtf" "xlsx" "odp" "ppt" "pptx"))

(setq dirvish-open-with-programs
    `((,dirvish-audio-exts . ("mpv" "%f"))
      (,dirvish-video-exts . ("mpv" "%f"))
      (,dirvish-libre-exts . ("libreoffice" "%f"))
      (("html") . ("qutebrowser" "%f"))
      ))
```
