### ISSUE TITLE
[Feature Request] Add a dirvish-last-session command

### ISSUE THREAD

**Issue by nicketson** [alexluigit/dirvish#125]
When using `dirvish-reuse-session`, it would be nice to have a command that switches to the last fullscreen session without prompting for a path. If there isn't an existing fullscreen dirvish session, it would prompt for a path like the normal `dirvish` command.

I suppose this could instead be implemented as a user option that would change the behavior of the `dirvish` command.

Thoughts?

**Comment by nicketson** [comment]
`dirvish-resume-session` might be a better name than `dirvish-last-session`

**Comment by alexluigit** [comment]
Did you mean resume the session and show the latest entry of the session regardless of `default-directory`?

**Comment by nicketson** [comment]
> Did you mean resume the session and show the latest entry of the session regardless of `default-directory`?

Yes, exactly.

Great job BTW. Dirvish is exactly what I've been looking for for years.

**Comment by alexluigit** [comment]
You can make it the default behavior by setting `dirvish-reuse-session` to 'resume.

Alternatively, make a custom command:
```emacs-lisp
(defun my/dirvish-resume ()
  (interactive)
  (let ((dirvish-reuse-session 'resume))
    (dirvish)))
```

**Comment by nicketson** [comment]
> You can make it the default behavior by setting `dirvish-reuse-session` to 'resume.
> 
> Alternatively, make a custom command:
> 
> ```emacs-lisp
> (defun my/dirvish-resume ()
>   (interactive)
>   (let ((dirvish-reuse-session 'resume))
>     (dirvish)))
> ```

Thanks, that's perfect!
