### ISSUE TITLE
[Feature Request] Dim highlight of inactive windows

### ISSUE THREAD

**Issue by Patryk27** [alexluigit/dirvish#127]
Hi,

After splitting the window it's not possible to tell which one has the focus:
![image](https://user-images.githubusercontent.com/3395477/185083362-e7231ec3-2390-47c2-bd23-af8150537a63.png)

Not sure if that's Doom Emacs doing something (e.g. hiding a caret that should be there), but maybe the unfocused window(s) could have e.g. gray highlight instead of the blue one?

Thanks;

**Comment by alexluigit** [comment]
Now you tell the focused window by the path segment on the header line.

> maybe the unfocused window(s) could have e.g. gray highlight instead of the blue one

It a good idea, but doing so we would have to define a new face `dirvish-hl-line-inactive` or something like that, which might looks a little bit confusing.  Maybe we can disable the line highlighting in the inactive dirvish window.
