### ISSUE TITLE
[Bug] Buffer closed after navigating in dirvish

### ISSUE THREAD

**Issue by m-ar-c** [alexluigit/dirvish#128]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I am just beginning to try dirvish and I like it very much so far. There's a behavior that might be a bug : after opening and navigating in dirvish, and closing dirvish, previously opened buffer might be deleted.

### Steps to reproduce

- An emacs frame with one window with buffer `A` open
- `M-x dirvish`
- `^^^^` (go to two parent folder)
- `q`
- **buffer `A` is deleted. Even if there were unsaved edits in the buffer/file, no question asked.**

Also doing the same thing :
- An emacs frame with one window with buffer `A` open
- `M-x dirvish`
- `^^` (go to the parent folder)
- `q`
- `M-x dirvish`
- `^^` (go to the parent folder)
- **buffer `A` is deleted. Even if there were unsaved edits in the buffer/file, no question asked.**

### Expected behavior

- An emacs frame with one window with buffer `A` open
- `M-x dirvish`
- `^^^^` (go to two parent folder)
- `q`
- **window/buffer configuration exactly as it was before using dirvish, as I didn't opened any file. No buffer deleted !**

Or

- An emacs window with buffer `A` open
- `M-x dirvish`
- `^^` (go to the parent folder)
- `q`
- `M-x dirvish`
- `^^` (go to the parent folder)
- **window/buffer configuration exactly as it was before using dirvish, as I didn't opened any file. No buffer deleted !**

### OS

Linux

### Emacs Version

27

### Emacs Configurations

custom

**Comment by m-ar-c** [comment]
It doesn't happen when I remove all my .emacs customization. I'll try to pinpoint what is causing this behavior.

**Comment by m-ar-c** [comment]
There was the following in my config along with the explaining comment. Without it the issue is gone.

``` elisp
;; When moving to parent directory by `^´, Dired by default creates a new
;; buffer for each movement up. The following rebinds `^´ to use the same
;; buffer.

(add-hook 'dired-mode-hook
 (lambda ()
  (define-key dired-mode-map (kbd "^")
	(lambda () (interactive) (find-alternate-file "..")))
  ))
```

LIke most things in my config I don't remember where I got it, when I put it there or if it is useful anymore ^^ So I'm removing it. Problem solved (for me, but I don't know if dirvish should be compatible with that, so I'll let you close it if it's not the case).

**Comment by alexluigit** [comment]
See: https://github.com/alexluigit/dirvish/discussions/102
