### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by jmburgos** [alexluigit/dirvish#129]
I noticed that after a recent update the functions the functions `dirvish-copy-file-name `and `dirvish-copy-file-path` are not available anymore.  When I try to call them I get this:
```
Autoloading file /home/julian/.emacs.d/elpa/dirvish-20220817.1003/dirvish.elc failed to define function dirvish-copy-file-name
Autoloading file /home/julian/.emacs.d/elpa/dirvish-20220817.1003/dirvish.elc failed to define function dirvish-copy-file-path
```
Have they been moved to one of the extensions?

**Comment by alexluigit** [comment]
They are autoloaded now.

**Comment by jmburgos** [comment]
Great, thanks!
