### ISSUE TITLE
[Feature Request] Integration with desktop.el and show the number of killed lines in the header

### ISSUE THREAD

**Issue by overideal** [alexluigit/dirvish#133]
Before stating my two small feature requests I just want to say that I am very impressed by this package. It feels extremely polished and I hope it will be integrated into core Emacs at some point in the future (it's that good!).

1. Integration with desktop.el
At the moment,  desktop.el saves the dirvish buffers, but does not restore them. I tried adding
```
(add-to-list 'desktop-buffer-mode-handlers
			 '(dirvish-mode . dired-restore-desktop-buffer))
```
and that seems to work, but the only problem is that the mode line and buffer line are blank until the buffer is redisplayed.

2. It would also be convenient to add the option of an indicator to the header or mode line that shows how many files in the currently displayed dired buffer are hidden (i.e. were previously killed by e.g. `dired-do-kill-lines`).

**Comment by alexluigit** [comment]
Thanks for the kind words!

Added dirvish-desktop-save-mode at 950055e.

> 2. It would also be convenient to add the option of an indicator to the header or mode line that shows how many files in the currently displayed dired buffer are hidden (i.e. were previously killed by e.g. `dired-do-kill-lines`).

Maybe we can improve the `omit` mode line segment and make it to display the number of omitted files, but it seems not easy to keep track of the file count of `dired-do-kill-lines`.

**Comment by overideal** [comment]
Hi, thanks for all your hard work.
Regarding 1.: I am not that thrilled about using an extra file to save/restore Dirvish. If every other major mode works with the desktop restore function, then why not Dirvish?
Indeed, one could e.g. try
```
(defun dirvish-restore-desktop-buffer (_file-name _buffer-name misc-data)
  (let* ((dired-dir (car misc-data))
         (dir (if (consp dired-dir) (car dired-dir) dired-dir)))
    (if (file-directory-p (file-name-directory dir))
        (with-demoted-errors "Desktop: Problem restoring directory: %S"
		  (let ((buf (dirvish--noselect dired-dir)))
			;; The following elements of `misc-data' are the keys
			;; from `dired-subdir-alist'.
			(with-current-buffer buf
			  (mapc #'dired-maybe-insert-subdir (cdr misc-data)))
			buf))
      (message "Desktop: Directory %s no longer exists." dir)
      (when desktop-missing-file-warning (sit-for 1))
      nil)))

(add-to-list 'desktop-buffer-mode-handlers
			 '(dirvish-mode . dirvish-restore-desktop-buffer))
```
This is a small modification of the code from `dired-restore-desktop-buffer`. In my limited testing it seems to work fine, though of course I don't know if there are edge cases or if important information is lost. The problem I mentioned above with blank mode-lines were fixed by your recent bugfix.
I also want to metion that with the current implementation (the one using an extra file) I also had problems of only some dired buffers restoring.

Regarding 2: It was just a random idea and I hoped there was some obvious way to do it, like maybe advising `dired-kill-line`. But it's really not that important. If you think it has a high potential for bugs or unexpected cases creeping in or simply is too much work, then that's totally fine by me.
