### ISSUE TITLE
[Bug] Split window and consult-buffer

### ISSUE THREAD

**Issue by overideal** [alexluigit/dirvish#136]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I am reporting a couple of probably related bugs.
For all, first follow the "Steps to reproduce".
1. The first bug is independent of consult.
Open dirvish in a directory (e.g. C-x C-f ~/.emacs.d C-j).
Splitting the screen in half (C-x 3) creates a **new** dirvish buffer also visiting .emacs.d.
Is this supposed to be this way? Ordinary dired behaves differently (namely it just reuses the same buffer)
and I vastly prefer that. In particular, by splitting the screen a couple of times we suddenly have tons of dirvish buffers visiting the same directory!

2. For the second bug, open two different directories, say .emacs.d and Downloads in dirvish (using C-x C-f).
With the selected window visiting say .emacs.d, calling consult-buffer and selecting Downloads switches to the Downloads
buffer, but header and modeline still show the information of .emacs.d!

3. For the third bug, start with a full screen scratch buffer, split the screen in half (C-x 3) and switch in the right window to the Downloads Dirvish buffer. Then switch focus to the left window and call consult-buffer. Typing in "Downloads" will now create a new Downloads buffer for every keystroke!

Maybe one more comment: I think you did a great job with the header and modeline. They look fantastic. However, to me they seemed to behave a bit weird sometimes. For instance, in my issue https://github.com/alexluigit/dirvish/issues/133 I mentioned that they prevent me from directly using desktop.el in order to save and restore dirvish buffers. Is there a built-in function to "refresh" header and modeline for the dirvish buffer (force-mode-line-update shows no effect for dirvish buffers for me)?

### Steps to reproduce

Run emacs -Q and evaluate
```
;; Add dirvish, consult, compat to load-path.
(require 'dirvish)
(dirvish-override-dired-mode)
(setq dirvish-header-line-format '(:left (path) :right (index free-space))
      dirvish-header-line-height (cons 22 22)
      dirvish-mode-line-format nil
      dirvish-mode-line-height (cons 15 15))
(require 'consult)
```
Version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)

### Expected behavior

1. Like in dired, don't have many dirvish buffers visiting the same directory.
2.,3. Obvious.

### OS

Linux

### Emacs Version

29

**Comment by alexluigit** [comment]
I hope https://github.com/alexluigit/dirvish/commit/8a597572848086713ec069a886220f8beddfd3f3 solved 1,2,3.

I'm not sure if it fixes the mode-line issue for you, the `desktop-buffer-mode-handlers` machinery has a couple of restrictions on buffer creation, I'll suggest using `dirvish-desktop-save-mode` instead.

**Comment by overideal** [comment]
I think the first commit already solved all three bugs. Nice job!
