### ISSUE TITLE
Wdired mode is unusable

### ISSUE THREAD

**Issue by muihlinn** [alexluigit/dirvish#137]
I'm not sure if it's a bug or I'm missing something (probably). Despite it worked well some time ago, current wdired implementantion is unusable.

Once I enter on wdired there is no cursor, editing bindings like `C-e` jus't dont work, cannot visually use regions, rectangles, and anything I type goes in the begining of the filename, making the last key pressed the first in the filename, e.g if I type key on it'll become yek followed by whatever the filename is.

**Comment by alexluigit** [comment]
Are you in the latest commit? I'm not able to reproduce this on my end with `emacs -q`.

**Comment by muihlinn** [comment]
As witn the latest elpa version widired mode works as intended, I just close the issue
