### ISSUE TITLE
[Bug] Two small dirvish-side issues

### ISSUE THREAD

**Issue by jdtsmith** [alexluigit/dirvish#140]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Two small issues:

1. The dirvish-side frame is resized when the window gets resized, but the file+dir listing itself is not updated until you up/down arrow.  
2. dirvish-side's ability to expand the hierarchy to reveal the current file starting from the project is amazing.  It only appears to work when the dirvish-side buffer _already exists_, however.  When a new dirvish-side buffer is made, it requires two invocations to get this "auto-reveal".

### Steps to reproduce

1. Start a dirvish-side but find it's too narrow, so widen the frame. Notice the listings remain the same, switch to the dirvish-side window, down arrow, and the file+dir formatted listings get updated.
2. In a fresh Emacs session (with subtree/expand configured), open a file nested deep in a project.  Invoke dirvish-side from this file's buffer.  Notice that the top level unexpanded project directory listing is displayed. 

### Expected behavior

1.  dirvish-side listings get updated after the window size is reconfigured.
2. The subtree gets expanded to show the current file whether the dirvish-side buffer already exists or is created anew.

### OS

MacOS

### Emacs Version

28

**Comment by alexluigit** [comment]
Let me know if 4a6f4b4 works.

**Comment by jdtsmith** [comment]
Yes on both!  Thanks.
