### ISSUE TITLE
[Bug] Ftp with dirvish always has one file/folder missing

### ISSUE THREAD

**Issue by sebastianappler** [alexluigit/dirvish#143]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When using dirvish with ftp one file/folder is always missing. If there's only one it shows empty.

### Steps to reproduce

- `C-x C-f` /ftp:user@hostname: `RET`
- Visit a location with files or folders.
- Use `C-x C-f` in location to see what's missing.

![dirvish-ftp-missing-folder](https://user-images.githubusercontent.com/13065474/189529700-96baa3ee-15bf-4b80-8f04-aaa005c2df1e.png)

### Expected behavior

All files/folders should be listed when using ftp with dirvish.

### OS

Linux

### Emacs Version

gccemacs-28

### Emacs Configurations

Doom Emacs

**Comment by alexluigit** [comment]
Let me know if 2b45839 fixed it.

**Comment by sebastianappler** [comment]
Thank you for reaching out!

I tried the commit but it seems the issue still persists for me.
Let me know if I can provide anything else.

**Comment by alexluigit** [comment]
Will the missing one revealed if you set `dirvish-use-header-line` to nil?

**Comment by sebastianappler** [comment]
That did the trick!
When I disabled the header line I can see all folders.

![dirvish-ftp-no-header-line](https://user-images.githubusercontent.com/13065474/189658296-ff52610c-1791-4c53-a6d9-13aeda2f1e5d.png)

I tested /ftp:anonymous@ftp.gnu.org:/gnu/emacs/ and for what I can see it seems like `README.olderversions` is missing. You can also see in the down right corner that the first item selected is 2 / 97.

![ftp-gnu-emacs](https://user-images.githubusercontent.com/13065474/189658785-983307d3-2668-4632-a5ba-6288228f40b9.png)

**Comment by alexluigit** [comment]
Feel free to reopen if the problem persists after af4b49c.

**Comment by sebastianappler** [comment]
Thank you, keep up the good work!
