### ISSUE TITLE
[Feature Request] Rationale behind line truncation?

### ISSUE THREAD

**Issue by karthink** [alexluigit/dirvish#144]
This is not a feature request (or a bug), just a question. In the single window mode (with `dirvish-override-dired-mode`), I have trouble parsing listings like this:

![2022-09-11-112256_690x569_scrot](https://user-images.githubusercontent.com/8607532/189543216-e81a913a-c024-4c84-9cc1-d6c952895321.png)

I can run `toggle-truncate-lines` on a hook afterwards to fix it, but I was wondering: what is the rationale for this in the first place?

**Comment by alexluigit** [comment]
See: https://github.com/alexluigit/dirvish/issues/33#issuecomment-1134384850
