### ISSUE TITLE
[Bug] Emacs 27 does not define font-lock-doc-markup-face

### ISSUE THREAD

**Issue by gcv** [alexluigit/dirvish#146]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Dirvish uses `font-lock-doc-markup-face`, which was only introduced in Emacs 28. This does not break Dirvish in Emacs 27, but results in many errors in the `*Messages*` buffer.

One possible fix is to conditionally include a definition of this face:

```
(when (version< emacs-version "28.0")
   (defface font-lock-doc-markup-face
    '((t :inherit font-lock-constant-face))
    "Emacs 28 backfill"
    :version "28.1"
    :group 'font-lock-faces)
   (defvar font-lock-doc-markup-face 'font-lock-doc-markup-face))
```

Alternatively, just use `font-lock-constant-face` directly.

### Steps to reproduce

Launch Dirvish in Emacs 27 and look at the `*Messages*` buffer.

### Expected behavior

No errors.

### OS

MacOS

### Emacs Version

27

**Comment by alexluigit** [comment]
Thank you for the report!
