### ISSUE TITLE
Question about starting dirvish without overriding dired-mode

### ISSUE THREAD

**Issue by muihlinn** [alexluigit/dirvish#147]
Before recent updates I was able to start dirvish over a dired buffer without having to override dired for all dired buffers. This doesn't seem the case now as dirvish won't start. 

After a quick look to dirvish source looks like calling dirvish with a path will do it, but evaluating ```(dirvish "~/.emacs.d")``` always returns `nil` not doing anything else.

What I'm missing here?

**Comment by alexluigit** [comment]
I think 737a71371ebfe53b63acb9d5112f91993e928bfb fixed this.
BTW dirvish-layout-toggle might be a better command for this job because it can also do dirvish -> dired, and it also works for `dirvish-side/dirvish-fd`

**Comment by muihlinn** [comment]
Well, it does as long as I have  set `dirvish-override-dired-mode` which is something I'd like to avoid. 
For some workflow reasons [which I can't avoid by now due lots of legacy issues I'm solving slowly] I need/want to start dirvish session for the current directory only (as it used to work), going to plain dired for each subsequent dired call.

**Comment by alexluigit** [comment]
> I was able to start dirvish over a dired buffer without having to override dired

This behavior is just a coincidence rather than designed this way, in principle dirvish expect `dirvish-override-dired-mode` is enabled to work correctly. Not sure why would you want a plain dired,but you may try these options https://github.com/doomemacs/doomemacs/pull/6760#issuecomment-1243687587.

**Comment by muihlinn** [comment]
> Not sure why would you want a plain dired,

mostly because I do maintain some projects for which me (and others) have written a boatload of small utilities along the years which do a wide variety of operations, often involvimg renaming files and refreshing the buffer. 

Dirvish isn't [yet] smart enough to keep the cursor over the renamed file after a buffer refresh, and that's an issue when there are hundreds of small files. Anyway, too specific kind of issues to bother anyone else.  I'm patching when I have the time.
