### ISSUE TITLE
[Bug] Problem with filenames with whitespaces

### ISSUE THREAD

**Issue by dvzubarev** [alexluigit/dirvish#151]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

filename is truncated when showed in subtree overlay
https://i.imgur.com/GUiBPAu.png
I failed to do any operation of this file because it "does not exist".

### Steps to reproduce

1. Create a directory a directory with one file `12 Monkeys 1995 2160p.mkv.txt`
2. Use `dirvish-subtree-toggle` on this directory
3. In my case, the filename is truncated in the subtree
https://i.imgur.com/GUiBPAu.png
When showing all details:
https://i.imgur.com/P8asO9v.png

### Expected behavior

I would expect to see full name in subtree overlay

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Doom Emacs

### Anything else

I use dirvish configuration from your PR in doom. Also I commented out all other related to dired configurations in the module.

**Comment by alexluigit** [comment]
Thanks, let me know if the latest update fixed this.

**Comment by dvzubarev** [comment]
Thanks, its fixed now.
Not a big problem but If you create empty folder and toggle subtree on it:
https://i.imgur.com/FaFwPFi.png
there is string `//DIRED-OPTIONS// --quoting-style=literal`
