### ISSUE TITLE
[Bug] subtree is not working on remote host

### ISSUE THREAD

**Issue by dvzubarev** [alexluigit/dirvish#154]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

It stopped working in https://github.com/alexluigit/dirvish/commit/a877ba816f907daea2d86bd10754bec6484e753a commit.
There is no error, only message in `*Messages*` - `(#<subr tramp-get-connection-property> 2)`

### Steps to reproduce

1. Put cursor on a directory on remote host
2. `M-x dirvish-subtree-toggle`

### Expected behavior

Subtree is toggled

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Doom Emacs

**Comment by alexluigit** [comment]
Let me know if 4f636bf fixed it. Thanks for bringing it to my attention.
