### ISSUE TITLE
[Bug] Weird interaction with tab-bar-mode and frames.

### ISSUE THREAD

**Issue by KaranAhlawat** [alexluigit/dirvish#156]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I have a function in my `server-after-make-frame-hook` that sets up a bunch of tab-bar tabs.
Inside, I'm also opening three different directories in three different tabs. Now, if I switch to any of the three tabs, and open a file from that directory from within dirvish itself, the dirvish buffer in the other two tabs either gets killed, duplicated in other tabs, or the document itself opens in two or more tabs (the inteded tab + others).

### Steps to reproduce

1. Add the function (linked below) to `server-after-frame-make-hook`.
2. Restart the daemon (for good measure).
3. Spawn an emacsclient frame.
4. Switch to a tab (Org, Agenda, or Books).
5. Open document in tab.
6. Buffers get displaced.

### Expected behavior

Each dirvish buffer should not be affected by the activity of the others in different tabs.

### OS

Linux

### Emacs Version

gccemacs-29

### Emacs Configurations

https://github.com/KaranAhlawat/core/blob/2c772a9fc6af10a06f20c13108ea73b7079aa68d/managed/emacs/modules/manage.el#L39

### Anything else

Attaching a recording for clarity.
[Kooha-10-11-2022-23-22-30.webm](https://user-images.githubusercontent.com/56113511/195164530-6a228ed5-5ef8-449c-9318-0425e6ba6c44.webm)

**Comment by alexluigit** [comment]
Thanks for reporting this! 
Please let me know if 4813c66 fixed this.

**Comment by KaranAhlawat** [comment]
Yes, that seems to have fixed the issue. Thanks for the speedy response and fix!
