### ISSUE TITLE
[Bug] Toggle `dirvish-emerge-mode` is not applied

### ISSUE THREAD

**Issue by vantu5z** [alexluigit/dirvish#158]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Toggle `dirvish-emerge-mode` applied to buffer only once.
1. turn on mode (and apply it to buffer)
2. turn off mode (and apply)
3. next attempts show only: `Dirvish-Emerge mode enabled(diable) in current buffer`

### Steps to reproduce

Call `dirvish-emerge-mode` few times.

### Expected behavior

Toggle `dirvish-emerge-mode` and apply to buffer

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Doom Emacs

### Anything else

If change line 515:
from: `(unless dirvish-emerge--group-overlays (dirvish-emerge--apply)))`
to: `(dirvish-emerge--apply))`
Maybe it's not right, and lead some other issues, but it fix mode toggle.

**Comment by alexluigit** [comment]
Thanks for your report! And sorry for the late response.
