### ISSUE TITLE
[Bug] `dirvish-media--metadata-from-mediainfo` breaks with fish shell

### ISSUE THREAD

**Issue by gekoke** [alexluigit/dirvish#161]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

When using the fish shell, file info previews return nil for all values.
![image](https://user-images.githubusercontent.com/63151928/199792334-deaafe02-b9c9-41af-90ca-ae4d86c23e87.png)

This is caused by fish's handling of `$` symbols:
```fish
(fish: Expected a variable name after this $\. mediainfo --Output=$ 'General ^)
```
Arising from this line:
https://github.com/alexluigit/dirvish/blob/ec4100612b2e93d9e188e7eab4c144b45f3547ee/dirvish-widgets.el#L251

When removing the `$`, both fish and Bash handle the command correctly as far as I can tell. Is there any reason for this symbol in the command, or is it redundant?

### Steps to reproduce

Preview a file with "mediainfo" and "pdfinfo" binaries in path, and fish as login shell.

### Expected behavior

File info previews display non-nil file metadata

### OS

Linux

### Emacs Version

28

### Emacs Configurations

Doom Emacs

**Comment by alexluigit** [comment]
Hi @gekoke , I totally forget why there is a "$" here, maybe a zsh thing but I'm not sure. I tried your solution for a while and it seems working fine. Thanks for your report!
