### ISSUE TITLE
[Feature Request] Automatically close preview buffers

### ISSUE THREAD

**Issue by jcguu95** [alexluigit/dirvish#164]
**Is your feature request related to a problem? Please describe.**

I have a library of pdfs in a folder. Dirvish allows me to quickly preview what the pdf is about in the preview window. However, that window is actually a buffer loading the book. This wastes some memories.

After I found the book I want, I notice that all of those pdf buffers are still open. Ideally, they should be killed after I move focus away from them. Also, if one pdf has already been opened by the user before the dirvish session, moving focus away from it should not kill that buffer. This makes it a bit hard to design and implement.

**Describe the solution you'd like**
1. Instead of loading the whole pdf in one blow, just let the user preview the first page.
2. When the user move focus away from one previewed file, kill the buffer for that preview.

**Comment by alexluigit** [comment]
Did you tried this?
https://github.com/alexluigit/dirvish/blob/main/docs/CUSTOMIZING.org#preview-pdf-files-with-generated-thumbnail
