### ISSUE TITLE
[Bug] RET on '..' entry should go to parent directory

### ISSUE THREAD

**Issue by zackw** [alexluigit/dirvish#170]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Pressing <kbd>RET</kbd> when a file is selected in either a Dirvish or Dirvish-augmented-Dired buffer visits the file.  Pressing <kbd>RET</kbd> when a directory is selected also visits the directory, *except* when the directory in question is `..`, in which case it prints an error in the echo area and does nothing.  This is inconsistent with the behavior of plain Dired, which will visit the parent directory if you press <kbd>RET</kbd> when point is on `..`, and also means that, as far as I can tell, the *only* way to navigate to the parent directory from the keyboard is with <kbd>^</kbd>, which is not what my fingers are used to.

### Steps to reproduce

After freshly installing Dirvish (from MELPA) I invoked `dirvish-override-dired-mode`, visited a random directory and then, as is my habit, put point on the line for `..` and pressed <kbd>RET</kbd>, expecting this to load the parent directory.

### Expected behavior

Pressing <kbd>RET</kbd> when `..` is selected should invoke `dired-up-directory`.

### OS

Linux

### Emacs Version

27

### Emacs Configurations

https://git.sr.ht/~zackw/dot-emacs/

**Comment by josephmturner** [comment]
I notice this bug also on Emacs 29

**Comment by rosstimson** [comment]
Overal project looks amazing but this seriously confused me when trying out Dirvish and had me running back to Dired.  Will definitely configure Dirvish as my go to file manager if this issue gets solved.

**Comment by rosstimson** [comment]
Oh, I should've mentioned that I use `exa`.  And this is on macOS (various versions) and Emacs 28.2.
