### ISSUE TITLE
Preview on bottom with Doom

### ISSUE THREAD

**Issue by Henny35P** [alexluigit/dirvish#18]
Hey, I've been using this package for a while and I'm really enjoying it (was using ranger.el before) but i have this problem where the preview on dirvish-toggle-fullscreen is at the bottom and it's really small.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/59944004/158921713-02032a44-9aae-4c30-8d29-dfc72b724153.png">
I tried playing around with dirvish-peek-display-alist but nothing seemed to change anything nor did changing backends of dirvish-peek-backend.
I don't know a lot about Emacs, so any help would be appreciated.

**Comment by alexluigit** [comment]
Hi Henry, 
I'd love to help but I can not reproduce it with a minimal config. I guess the following info might be helpful:
1. doom config (at least the Dirvish part) 
2. the value of your `display-buffer-alist`
3. your customized window placement config (if any)

**Comment by Henny35P** [comment]
Thanks, i removed the +all flag and it works like it should now.
Thanks for your help and the package!
