### ISSUE TITLE
-m option on ffmpegthumbnailer 2.1.1 breaks it

### ISSUE THREAD

**Issue by muihlinn** [alexluigit/dirvish#19]
https://github.com/alexluigit/dirvish/blob/69e13485da668d60b347b2fce69f305e53d4e7b9/dirvish.el#L1033

ubuntu 20.4, current updates, emacs 27.2.

it never generates the thumbnail with this switch, after removing it and reevaluating the `defun` works fine.

PS: I know 2.1.1 is a pretty old version, but it's what is installed from apt sources.

**Comment by alexluigit** [comment]
Thanks for reporting. I guess the '-m' flag requires a `ffmpegthumbnailer` version that is greater than 2.1.1. Here's the documentation for it: 
```shell
# ffmpegthumbnailer -h (on 2.2.2)
-m      : prefer embedded image metadata over video content
```
This might be a much sensible default IMO.
Here's a comparison with a video file with embedded thumbnail
- with '-m':
![withm](https://user-images.githubusercontent.com/16313743/159449191-c518079b-9263-4bd4-85e0-49e9630b3d53.png)

- without '-m'
![withoutm](https://user-images.githubusercontent.com/16313743/159449214-a213322a-817e-4f28-8505-a20462b6457b.png)

 I'd suggest you to update your `ffmpegthumbnailer` to the latest version (2.2.2), but if that's not applicable to you, you can define your own dispatchers and replace the `video` dispatcher in `dirvish-preview-dispatchers` with the new one.

**Comment by alexluigit** [comment]
>May worth making a check before using it, and/or mentioning it in the documentation.

Thanks for your suggestion. Will link this issue in the Configuration.org

**Comment by alexluigit** [comment]
Here's a workaround for people want to stick with `ffmpegthumbnailer` 2.1.1:

```emacs-lisp
(dirvish-define-preview video-thumbnail-fix (file dv)
  "Display a video thumbnail with width of DV's preview window."
  (when (string-match "video/" (or (mailcap-file-name-to-mime-type file) ""))
    (let* ((p-win (dv-preview-window dv))
           (width (dirvish--preview-image-size p-win))
           (height (dirvish--preview-image-size p-win 'height))
           (cache (dirvish--get-image-cache-for-file file width ".jpg")))
      (if (file-exists-p cache)
          `(image . ,(create-image cache nil nil :max-width width :max-height height))
        `(image-cache . ("ffmpegthumbnailer" "-i" ,file "-o" ,cache "-s" ,(number-to-string width)))))))

(setq dirvish-preview-dispatchers
      (cl-substitute 'video-thumbnail-fix 'video dirvish-preview-dispatchers))
```

**Comment by alexluigit** [comment]
Hi @muihlinn, I finally decided to take care of it cause the workaround looked ugly.
Please let me know if https://github.com/alexluigit/dirvish/commit/2a6c18ae17c472f5200c0b7ed01e726e55ca663f works.

**Comment by muihlinn** [comment]
I'll try it tonight in the laptop because after tracing the problem I just posted the issue, reverted my edit and installed 2.2.2 in this machine. Thanks for the quick fix, I'll let you know.

**Comment by muihlinn** [comment]
@alexluigit Found another suitable computer and it works fine.

**Comment by alexluigit** [comment]
Thanks for your confirmation :)
