### ISSUE TITLE
font size is larger in dirvish windows

### ISSUE THREAD

**Issue by jekor** [alexluigit/dirvish#2]
dirvish windows appear to be using a larger font size than other windows, and there appears to be no custom setting related to it. Additionally, if I try to reduce the font size with `text-scale-adjust`, it will be smaller than other windows (the scale seems to be different overall, rather than a step up from "normal" size) and will run into the header above. I see how the header scale can be adjusted, but the height seems to remain the same (just the text is smaller).

It would also be nice to have customization to help make the windows more compact:

- adjust/remove space before icons
- adjust/remove space after icons
- remove `»`
- remove scollbars
- remove other spacing (outside of the line highlight area)

My first impression of dirvish is positive, and I look forward to using it more. Thanks for publishing it.

**Comment by alexluigit** [comment]
Hi Chris, thanks for reporting.

> dirvish windows appear to be using a larger font size than other windows, and there appears to be no custom setting related to it. Additionally, if I try to reduce the font size with `text-scale-adjust`, it will be smaller than other windows (the scale seems to be different overall, rather than a step up from "normal" size) and will run into the header above. I see how the header scale can be adjusted, but the height seems to remain the same (just the text is smaller).

The reason to have a bigger font size in dirvish body is that  the text in this buffer is not only plain text but also a "dired object", which is different from a regular text buffer, I just wanted to make it look much obvious. 
You can change this behavior by customizing `dirvish-body-fontsize-increment` and `dirvish-use-large-header`. 

I believe this is what you want. (please update to latest version first)
```
(setq dirvish-use-large-header nil)
(setq dirvish-body-fontsize-increment 0)
```

> 
> It would also be nice to have customization to help make the windows more compact:
> 
> * adjust/remove space before icons

Dirvish doesn't add anything before the icon, the space you saw there is actually added by Dired, seems that it can not be removed easily. Also, Dired might need this space to indicate that it's a new file/dir line, but I'm not sure about this. Anyways, I'll look into this and see if I can make this customizable.

> * adjust/remove space after icons

You can now do that with `(setq dirvish-icon-delimiter " ")`.
A caveat for setting this to a single space is it sometimes break the alignment of filename. (set it to "\t", which is the default value, can avoid this problem in most of the cases)

> * remove `»`

If I'm not mistaken,  what you are referring to is the arrow in window fringe, can `(set-fringe-style '(1 . 1)` solve this?
 
> * remove scollbars

Dirvish does not touch this setting, I think `(scroll-bar-mode -1)` should do the trick.

> * remove other spacing (outside of the line highlight area)
>  Again, dirvish doesn't touch this, try execute `(set-fringe-style '(1 . 1)`

> My first impression of dirvish is positive, and I look forward to using it more. Thanks for publishing it.

Thanks for your kind words and suggestions!

**Comment by alexluigit** [comment]
For newcomers, the option `dirvish-use-large-header` has been renamed to `dirvish-header-style`, see its documentation for more detail. Close this issue for now.
