### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by meliache** [alexluigit/dirvish#208]
We have `all-the-icons` and `vscode-icons` integration in `dirvish-icons.el`. I would like an additional attribute for using the icons from [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el). The package integrates [Nerd Font Icons](https://github.com/ryanoasis/nerd-fonts), which compared to all-the-icons has the advantage that you only need that font and don't need to install multiple fonts.

The developer already provides a [nerd-icons-dired](https://github.com/rainstormstudio/nerd-icons-dired) package that integrates from my first tests works with _dirvish_. I just thought it would be nice to have this as a _dirvish_ attribute, as it should be simple to implement in a similar way as the existing icon attributes.. An argument against including that in dirvish is that `nerd-icons-dired` so far has only 14 github stars, so it's not like it's super popular yet, but that is partly because it's so new.

**Is your feature request related to a problem? Please describe.**
The existing icon attributes work for me. `all-the-icons` is just a bit heavyweight in that it requires installing a bunch of fonts via `M-x all-the-icons-install`  and in case I don't like vscode-icons I think it's nice having an alternative..

**Describe the solution you'd like**
An additional `nerd-icons` attribute.

**Describe alternatives you've considered**
The icon font alternatives that I know, `nerd-icons` and `vscode-icons`, are already implemented in dirvish.

**Comment by alexluigit** [comment]
Thanks for the report.
See: https://github.com/alexluigit/dirvish/pull/201

**Comment by meliache** [comment]
Awesome, I had somehow overlooked #201, probably just searched the issues... Nerd Fonts is quite new so it's not complete surprising that there's sudden interest. Thanks for reviewing and merging that PR.
