### ISSUE TITLE
Slow navigation on remote host via TRAMP

### ISSUE THREAD

**Issue by jumper047** [alexluigit/dirvish#21]
I tries to use Dirvish with kubel (kubernetes UI for Emacs) to browse filesystem inside container, and it was extremely slow comparing to plain dired. Is it possible to add some sort of "remote" mode which will minimize unnecessary readings from the file system?

**Comment by alexluigit** [comment]
Good suggestion. I've push a patch for it, please try it out. For now I think a Dirvish session over TRAMP is somewhat usable, I'll see if I can make it much responsive though. Let me know what you think.

**Comment by jumper047** [comment]
Wow, that's was quick! Thank you, I'll try it ASAP and report back

**Comment by alexluigit** [comment]
I think I've pinned down the root causes of the issue. After these 2 commits I believe it is as fast as a regular dired (at least you won't tell the difference). Also, all the buffers within a Dirvish session is automatically reused.

**Comment by jumper047** [comment]
Just checked - now it's almost perfect, thank you! Just one little thing, current line highlighting changed to plain cursor in remote buffers. Is it possible to get it back?:)

**Comment by alexluigit** [comment]
Oh sorry I forgot to mention it, I've put line highlighting back in the latest commit, I guess it's going to land on MELPA soon.

**Comment by jumper047** [comment]
So, for me this issue is resolved completely! And thank you for this awesome package, I love it!
