### ISSUE TITLE
[Bug] Invalid `dirvish-emacs-bin`

### ISSUE THREAD

**Issue by summeremacs** [alexluigit/dirvish#211]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Hi there,
I just installed Dirvish and it has some odd behaviors. When I enter into any directory, I get this error in my Messages buffer:

error in process sentinel: dirvish-dir-data-proc-s: End of file during parsing
error in process sentinel: End of file during parsing

I'm running railwaycat Emacs 28.2 on MacOS Ventura. Also, I'm not a coder so I may be a little lost at times.

I don't have any other dired packages installed (I removed Dired+ to try this out), and it's still giving me that error and hanging for about 2 seconds anytime I enter a directory. Also, I have to invoke the dirvish-setup-menu and click on M-t for it to give me the different windows in my emacs frame, if not when I invoke any dired buffer/directory, it'll just look like a normal dired buffer.

All I have in my config for Dirvish is:   (dirvish-override-dired-mode)

Please let me know any info that I can provide which might be able to help you.

Thank you. 🙃

### Steps to reproduce

Entering any dired directory.

### Expected behavior

Just normal operation with no error messages.

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

Vanilla Emacs Railwaycat for MacOS

**Comment by summeremacs** [comment]
Okay, so somebody helped me and what it turns out is that I need to set the path for my emacs binary. So I have the following in my config:

```
  (dirvish-override-dired-mode)
  (setq dirvish-emacs-bin "/opt/homebrew/Cellar/emacs-mac/emacs-28.2-mac-9.1/bin/emacs-28.2")
```

Now, I have a problem that after I restart Emacs, that doesn't work anymore. I have to go back and re-eval it by hand. I'm not sure why, but the setq isn't working correctly. However, once I eval by hand, it does work. So I'll work on fixing that line up more so that it works after restart.

**Comment by summeremacs** [comment]
Okay, little update:

(setq dirvish-emacs-bin "path") does not work because it apparently works with (setq-default). I don't know why but somebody helped me figure it out.

**Comment by alexluigit** [comment]
Please let me know if [this PR](https://github.com/alexluigit/dirvish/pull/192) fixed this.
