### ISSUE TITLE
[Bug]  Video preview never finishes

### ISSUE THREAD

**Issue by Kenneth-Mata** [alexluigit/dirvish#217]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

I'm using ffmpegthumbnailer version 2.2.2 and the video preview doesn't work, i can see the ffmpegthumbnailer process happening but it never writes and just continues to execute until it stops

### Steps to reproduce

```lisp
;; Just loading a very minimal part of my config after doing emacs -Q
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/"))
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/"))
(package-initialize)

(require 'use-package)

(use-package use-package
	:config
	(eval-and-compile
		(setq use-package-always-ensure t
		      use-package-expand-minimally t)))

(use-package all-the-icons)
(use-package dirvish
  :init (dirvish-override-dired-mode)
  :config
  (setq dirvish-attributes '(all-the-icons file-time file-size))
  (setq delete-by-moving-to-trash t)
  (setq dirvish-header-line-height '(25 . 25)))
```

### Expected behavior

A video thumbnail being generated like in the demo gifs

### OS

Linux

### Emacs Version

29

### Anything else

![Screenshot_20230523_131435](https://github.com/alexluigit/dirvish/assets/92641443/3a2ab3d1-1bb7-4d0b-b361-b566d068b0de)

even when trying on a file that's less than 1mb

![Screenshot_20230523_131102](https://github.com/alexluigit/dirvish/assets/92641443/1fdd19b4-be80-4079-bf46-e172687fc606)

i'm getting dirvish from melpa, version ``20230519-1500``

**Comment by alexluigit** [comment]
I'm not able to reproduce this.  Maybe have a look into `dirvish-cache-dir`, is the thumbnail generated successfully?
