### ISSUE TITLE
performance issue with search

### ISSUE THREAD

**Issue by gitrj95** [alexluigit/dirvish#223]
hi, when using dirvish-fd, the process locks up. the search through transient in dirvish mode does the same. in contrast, consult-find appears much faster

is this just asynchrony at play? or is there something else at work?

i'm using an arm mbp. lmk if you need additional details

**Comment by dvzubarev** [comment]
`dirvish-fd` is slow because filtering is done via emacs regexes (see https://github.com/alexluigit/dirvish/pull/187 for details).
Try `dirvish-fd-ask`, It will prompt for a pattern and pass that pattern to fd (so filtering is done in fd).

**Comment by gitrj95** [comment]
why is this the default?
