### ISSUE TITLE
dirvish--get-filesize: Search failed: "\\(^[0-9.,]+[a-zA-Z]*\\).*total$"

### ISSUE THREAD

**Issue by xiaobing-huang** [alexluigit/dirvish#23]
I am trying to use dirvish-yank to copy a file to a destination folder, and got the error:
> dirvish--get-filesize: Search failed: "\\(^[0-9.,]+[a-zA-Z]*\\).*total$"

I tried two files, one file is successfully copied to the folder, and other one got failed.
And try to run "du" command in terminal, got below outputs
<img width="390" alt="2022-04-13_14-57-24" src="https://user-images.githubusercontent.com/32288091/163118449-70f1a351-2cbb-4c82-9771-ccf59ba530df.png">

**Comment by alexluigit** [comment]
Thanks for reporting. I believe 73701233095d472f4631c91729012fa338eca343 fixed this.
I don't know why there is a leading white space in the first `du` output, maybe a macOS thing.

**Comment by xiaobing-huang** [comment]
Thanks for quick response, it works now.
