### ISSUE TITLE
supress "Symbolic link to Git Controlled source file; follow link?" prompt

### ISSUE THREAD

**Issue by wwzhang** [alexluigit/dirvish#25]
Is that possible to suppress it? Likely, it might be suffice for the warning of linked file just one time for each folder?

BTW, it is possible to set dirvish to omit several file types for display? Such as not list the .DS_Store files on Mac.

**Comment by alexluigit** [comment]
If 5e2335601608f230f166d7f3a5418d43206141d7 failed to solve this, I would suggest you set `vc-follow-symlinks` to t globally, which is also what I did.

> BTW, it is possible to set dirvish to omit several file types for display?

Use `dired-omit-mode`  for this purpose
```emacs-lisp
(setq dired-omit-files (concat dired-omit-files "\\|^\\.DS_Store"))
```
See the `dired-x` [config](https://github.com/alexluigit/dirvish/blob/main/Configuration.org#complementary-packages)
