### ISSUE TITLE
Icon and filename alignment

### ISSUE THREAD

**Issue by ST-Saint** [alexluigit/dirvish#255]
Thanks for the great project. I wonder if I can make the filenames aligned after the icons.

<img width="258" alt="image" src="https://github.com/alexluigit/dirvish/assets/13213464/6d7909be-6ff3-4b45-9197-34ce852fa9a6">

**Comment by gekoke** [comment]
This is not something I experience:
![image](https://github.com/alexluigit/dirvish/assets/63151928/6cd775c4-c877-4b90-a454-17032910a45f)

**Comment by ST-Saint** [comment]
@gekoke which font do you use?

**Comment by gekoke** [comment]
> @gekoke which font do you use?

This screenshot was with `Iosevka Nerd Font-bold-normal-normal`, but any font (including non-monospace fonts) with any weight and style works for me.

**Comment by ST-Saint** [comment]
> > @gekoke which font do you use?
> 
> This screenshot was with `Iosevka Nerd Font-bold-normal-normal`, but any font (including non-monospace fonts) with any weight and style works for me.
> 
> Edit: oh, and this is with `nerd-icons`, not `all-the-icons`

Thanks, I wasn't aware of the `nerd-icons` attribute. Both `vscode-icon` and `nerd-icons` give me alignment but unfortunately `all-the-icons` doesn't
