### ISSUE TITLE
More dired-yank commands

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#26]
It would be nice if dired-yank provided specific commands for each possibility (commands for move, relalink, and symlink), so that I don't have to make them myself.

It would also be nice if support was added for hardlinks (and ranger's hardlinked_subtree subtree if possible). I use hardlinks way more often than symlinks because I don't have to worry about them breaking if I move files.

**Comment by alexluigit** [comment]
(In reply to https://github.com/alexluigit/dirvish/issues/34#issuecomment-1119190316)

> would it also be possible to have the equivalent of ranger's paste hardlinked subtree?

Turns out all I have to do is to replace the shell command for hardlink from "ln" to "cp -al"

> Also, could you add autoload cookies for the new yank commands?

How could I miss this, it was under my nose. Done.

**Comment by noctuid** [comment]
Great! Nice that it's just one command for hardlinks rather than the two in ranger.
