### ISSUE TITLE
Add back dirvish-sort-by-criteria or an equivalent

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#27]
I'd prefer to be able to bind a key directly to this, so that I could change the sorting method in two keypresses.  Having it was a lot faster for me than going through the current ls switches transient.

**Comment by alexluigit** [comment]
Hi @noctuid, I brought back the `dirvish-sort-by-criteria`, and renamed it to `dirvish-quicksort`, hope you like it.

**Comment by noctuid** [comment]
Thanks!
