### ISSUE TITLE
Precache images in the background

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#28]
Previously I was not using image preview with ranger.el (and the alternative packages) at all because it was too slow. Dirvish image preview is fast and instant once an image is cached. It might be nice if there was an option to cache the current directory in the background (maybe after a certain amount of idle time). Then it could be instant more of the time.

**Comment by alexluigit** [comment]
After https://github.com/alexluigit/dirvish/commit/4301888056c76649896750a117a2a6e776c50b77 this should work out of the box. You can play around with the `dirvish-auto-cache-threshold` variable if you feel the auto caching too aggressive.

**Comment by noctuid** [comment]
Thanks, I may need to tweak that variable, but it seems to be working fairly well.  Does it cache in any particular order, e.g. if I change the sorting will it cache around the current entry for the new sorting or does it not matter?

**Comment by alexluigit** [comment]
For now it does not respect the sorting of directories, but we can definitely do that on buffer reverting to get a better experience.
