### ISSUE TITLE
Double icon and keybind issue in doom emacs

### ISSUE THREAD

**Issue by arionrefat** [alexluigit/dirvish#3]
First, really liked you package, Keep up the good work. It's lot faster than ranger.el (without running daemon).
Second, I'm new to emacs world and still learning. I'm currently using doom emacs.

![image](https://user-images.githubusercontent.com/37513070/147206147-d2ae4ded-2717-43c7-9eea-18e1aa27fdca.png)

This is dirvish without configuring anything just added the lines that is shown in the README.
As you can see here the icons shows twice for some reason.
If I press 'h' or 'l' it does not go to up directory nor go to down directory (I have to press '-' or run command 'dirvish-up-directory')

if you take ranger, nnn or any other terminal file manger who uses vi keys, pressing 'h' goes back to prev directory and 'l' goes to next directory or opens a file.  It would be awesome if I can achieve that.

There is a bug maybe, if run 'dirvish-dired' by 'M-x' while on doom dashboard and press qq after opening 'dirvish-dired' then emacs hangs and cpu usages rises as you can see here otherwise pressing 'q' closes the window while I'm in a buffer. Again I'm new to emacs I may have done something wrong, If you need any more info please mention it.

![image](https://user-images.githubusercontent.com/37513070/147207375-fd990ced-88a6-4e8f-8e62-fe075930cda7.png)

PS: English is not my native language, please excuse my mistakes.

**Comment by arionrefat** [comment]
Here is a gif of that bug,
![image](https://user-images.githubusercontent.com/37513070/147209630-55021ff7-eeda-4537-9ced-f1733306629b.png)

**Comment by arionrefat** [comment]
Here is the gif of that bug,
![emacs](https://user-images.githubusercontent.com/37513070/147209744-5812602e-baf6-4742-80ab-2cb9cd22f65a.gif)

**Comment by chmouel** [comment]
I don't use doom emacs but  I had  all-the-icons-dired configured and it was showing me double icons, disabling it made it works...

(there is two bugs in there btw abotu the vim binding I personally not used to the vim keys so I rather not have them by default or at least being able to disable them if implemented)

**Comment by arionrefat** [comment]
Yea, that helps, disabling all-the-icons-dired works for me. Thank you
> (there is two bugs in there btw abotu the vim binding I personally not used to the vim keys so I rather not have them by default or at least being able to disable them if implemented)
>
Yeah a option would be nice.

Also is there any way I can toggle hidden/non-hidden files? I didn't any command for that

**Comment by alexluigit** [comment]
Hi Refatul, thanks for reporting.
For the replicate icon, I guess you have figured it out, disable +icons feature should work. I should have wrote better docs for doom users, sorry for that.

> if you take ranger, nnn or any other terminal file manger who uses vi keys, pressing 'h' goes back to prev directory and 'l' goes to next directory or opens a file. It would be awesome if I can achieve that.
> 

As @chmouel points out, I guess it would be better letting user to decide what keybindings to use.
Will `(map! :map dirvish-mode-map ...)` do the remapping?  I don't know for sure how to create keybindings in doom, sorry I'm mistaken.

> There is a bug maybe, if run 'dirvish-dired' by 'M-x' while on doom dashboard and press qq after opening 'dirvish-dired' then emacs hangs and cpu usages rises as you can see here otherwise pressing 'q' closes the window while I'm in a buffer. Again I'm new to emacs I may have done something wrong, If you need any more info please mention it.
> 

Yes, it's a bug, I believe this should be fixed in the latest commit, please try out and let me know if the problem still exists. (you can use _:pin_ keyword in your package! declaration to try it now, since melpa need some time to keep up the latest version)

Glad you like dirvish!

**Comment by arionrefat** [comment]
Thank you for the response, I will check it.

**Comment by alexluigit** [comment]
Sorry I didn't see your last question about file hiding, you can use `dired-omit-mode' to hide/show files, and hopefully you would see the "Omit: on/off" indication in the footer. You can customize `dired-omit-files' and `dired-omit-extensions' to your liking.

Here is my personal config. This makes `dired-omit-mode' hide/show all "dotfiles".
```emacs-lisp
(setq dired-omit-files
          (concat dired-omit-files "\\|^\\..*$")))
```

**Comment by arionrefat** [comment]
It works now.
First time it crashed with a message (i forgot) but now it seems working fine.

**Comment by edgar-vincent** [comment]
Would it be possible to disable `all-the-icons-dired-mode` in "dirvishified" buffers only in order to be able to use the `+icons` flag for Dired buffers? I tried playing around with hooks, but couldn't find a suitable configuration.

Thanks for your work!

**Comment by alexluigit** [comment]
> Would it be possible to disable `all-the-icons-dired-mode` in "dirvishified" buffers only in order to be able to use the `+icons` flag for Dired buffers? I tried playing around with hooks, but couldn't find a suitable configuration.
> 
> Thanks for your work!

Thanks for reporting. 
This issue should have been fixed in the latest commit.
Beware that there are also some other updates involving override dired with dirvish.
Enable `dirvish-override-dired-mode`  will make commands like `dired/dired-other-window/dired-jump/dired-jump-other-window` do their job in a 'dirvish' way. Hope you like it.

**Comment by edgar-vincent** [comment]
Excellent! This seems to solve the issue perfectly. Thank you!
