### ISSUE TITLE
Paste conflict alternative renaming to preserve extension

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#30]
It would be nice if there was an option to add to before the first period in the filename, so that the extension doesn't change.  Alternatively, it could add at the beginning. This is one thing that still annoys me about ranger since changing the extension breaks rifle, for example.

**Comment by alexluigit** [comment]
Did the option `dirvish-yank-new-name-style` fixed this for you? I guess `append-to-filename` is what you want. I would like to keep `append-to-ext` as the default since Dired/Emacs recognize files whose names end with ~ as backups, cheers.

**Comment by noctuid** [comment]
Thanks that works.  There is a problem if I try to do it multiple times though.  Not sure if this is how it was before, so I opened a separate issue (#38).
