### ISSUE TITLE
Used and total free space in modeline

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#31]
It would be nice if there were segments to show total free space and the total used space of the directory like in ranger.  Total free space would be more useful I think.

**Comment by alexluigit** [comment]
I've added the `free-space` mode-line segment. Besides we also have the `dirvish-total-file-size` command.

**Comment by noctuid** [comment]
`dired-toggle-marks` then `dirvish-total-file-size` is good enough.  I don't need this functionality often, but showing the free space is nice (I don't have much left). Thanks!
