### ISSUE TITLE
History navigation commands

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#32]
This is a fairly minor issue, but the equivalent of ranger's `:history_go` command would be nice to navigate forward and backwards in the history.  This is useful if you want to go back to a previous directory after having jumped far away either with a bookmark, find-file, or whatever command.  If it was only a 1 or 2 directories ago, it's faster to have a "go back" key than to use `dirvish-show-history`.

**Comment by alexluigit** [comment]
Now we have `dirvish-go-forward/backward-history` commands. You should be able to specify the step by prefixing a number such as C-u 2 (or just 2 in evil).

**Comment by noctuid** [comment]
> It's worth noting that dirvish-show-history shows the global history entries (across all Dirvish session) while the forward/backward command use the session local history. I hope this makes sense.

Yes, this makes sense to me.  Thanks!
