### ISSUE TITLE
Optional 2-pane mode and larger preview

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#33]
This is also minor. I love the 3-pane mode, but it might also be nice to be able to toggle into a 2-pane mode or make the preview area bigger. For example, in ranger, I have a key that toggles into 2 panes and makes the preview really big.

**Comment by noctuid** [comment]
A customizable pane ratio might also be nice (and could be used to handle the above cases).  I currently use `1,3,5` for ranger.  The middle pane is a little bigger in ranger, which helps fit long file names.

**Comment by alexluigit** [comment]
Please try out the `dirvish-switch-layout` command. The `dirvish-setup-menu` also get updated accordingly. Let me know what you think about them, thanks.

**Comment by alexluigit** [comment]
Also see the `dirvish-default-layout` user option.

**Comment by noctuid** [comment]
Yes, this is perfect!

The `dirvish-default-layout` documentation might also link to `dirvish-layout-recipes`.

One question:  It looks like long filenames are always truncated when only two panes are shown, even when "truncate long lines" is disabled.  With three panes, the behavior depends on "truncate long lines."  I prefer truncation, so this doesn't bother me, but do you know why this happens?

**Comment by alexluigit** [comment]
> It looks like long filenames are always truncated when only two panes are shown, even when "truncate long lines" is disabled. With three panes, the behavior depends on "truncate long lines."

This should have nothing to do with the pane numbers, have a look at the variable `truncate-partial-width-windows`.
