### ISSUE TITLE
Bookmarking multiple Dirvish windows doesn't work with Burly

### ISSUE THREAD

**Issue by Kungsgeten** [alexluigit/dirvish#35]
[Burly](https://github.com/alphapapa/burly.el) is a package by @alphapapa which lets you bookmark window and frame configurations. If I have two or more windows with Dired/Dirvish buffers in a bookmark, only one of them is restored when `dirvish-override-dired-mode` is activated. It seems like the other dired buffers are deleted.

**Comment by alexluigit** [comment]
Thanks for reporting, let me know if the latest commit fixed this for you.

**Comment by alexluigit** [comment]
I believe the latest commit fixed this. Please try it out, thanks.

**Comment by Kungsgeten** [comment]
Yes, it seems to work! Thanks!
