### ISSUE TITLE
Make Dirvish compatible with `auto-dim-other-buffers-mode`

### ISSUE THREAD

**Issue by Kungsgeten** [alexluigit/dirvish#36]
From the screenshots I see that you don't have any examples of more than one Dirvish instance at the time, so maybe Dirvish isn't meant to be used this way. However I often use Dired as a "dual-pane" file manager with one directory to the left and one to the right (two windows). I've set `dired-dwim-target` to `t`. This means that a `dired-do-copy` suggests the other window directory as the target.

When I try to have two Dirvish buffers side by side I noticed two issues:

1. `dired-do-copy` suggests one of them, not the other one. So if I am on the left window buffer it might suggest the left one instead of the right.
2. I'm using `auto-dim-other-buffers-mode` which visually makes windows without focus less prominent. This doesn't work very well with Dirvish. It is somewhat random, but usually the Dirvish window(s) always look like they have focus. So if run in "dual-pane" it looks like both have focus.

**Comment by alexluigit** [comment]
> `dired-do-copy` suggests one of them, not the other one. So if I am on the left window buffer it might suggest the left one instead of the right.

Does the latest commit fix this?

> So if run in "dual-pane" it looks like both have focus

The quickest way to solve this is to `(setq dirvish-face-remap-alist nil)`, or you can play around with this variable to see how to make it work well with `auto-dim-other-buffers-mode`

**Comment by Kungsgeten** [comment]
Yes the copying seems to work, even though I split the window when already in Dirvish. Thanks!

**Comment by alexluigit** [comment]
I've removed `dirvish-face-remap-alist`, this option seems to be too intrusive. Besides, the functionality this option provides can be replaced by `custom-theme-set-faces`. So now `auto-dim-other-buffers-mode` would play nicely with dirvish. I'm closing now, but feel free to reopen if anything is still broken.

**Comment by Kungsgeten** [comment]
Yes, it seems to work now
