### ISSUE TITLE
Handle pasting duplicates multiple times

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#38]
In ranger, if you keep pasting duplicates it will automatically increment the number (e.g. `foo_` then `foo_0` then `foo_1`.  It looks like with dirvish and both `append-to-filename` or `append-to-ext`, you can only paste a duplicate one time.  I get `foo1~.txt` the first time but not `foo2~.txt` the next time if I try to paste.  Instead dirvish overwrites `foo1~.txt`.  Dirvish should check if the new name exists as well instead of overwriting it.

**Comment by alexluigit** [comment]
It's a bug, the latest commit should fixed it. This commit also enables user to choose "No-for-all" (ensure new files for all duplicate file names).

**Comment by noctuid** [comment]
Thanks! Is there currently some option to choose a default (e.g. select "no-for-all" without prompting)?

**Comment by alexluigit** [comment]
Nice suggestion! Added `dirvish-yank-overwrite-existing-files`.

**Comment by Kabouik** [comment]
Sorry to hijack this old issue, but how exactly does Dirvish needs to be set up to expose the functions described here? I would like to be able to yank (copy) a folder and paste it (`y` `y`) in the same location but be prompted to give it a new name (_i.e._, duplicate that folder), but instead I just get the error stating that the source and destination are the same. I have the `dirvish-yank-menu` showing up when hitting `y`, but am I missing a `(require 'dirvish-*)`? 

[Edit: I found the `C` action, but I think it would make sense to have it listed in `dirvish-yank-menu`.]
