### ISSUE TITLE
Add other ranger mode line items

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#42]
It would be nice if dirvish had the remaining missing items from ranger's mode line, specifically everything that would be shown for the file in dired details mode.  I wouldn't need the size again (though someone might want it), but everything else is useful (permissions, # links, owner, group, mtime).

**Comment by alexluigit** [comment]
Thanks for the advice.
To make it much easier to customize, I did not prefix nor suffix any spaces to all the builtin file attribute segment. Here is an example config:
```emacs-lisp
;; (setq dirvish-mode-line-text-size 0.9)
(customize-set-variable
 'dirvish-mode-line-format
 '(:left
   (sort file-size " " file-user ":" file-group " " file-link-number symlink)
   :right
   (yank index)))
```

**Comment by noctuid** [comment]
Great, thank you.
