### ISSUE TITLE
Hide the cursor for `evil-mode`

### ISSUE THREAD

**Issue by zrquan** [alexluigit/dirvish#43]
通过 `find-file` 或者 bookmark 打开目录时光标没有隐藏，需要切换一次目录才会隐藏光标

<img width="543" alt="image" src="https://user-images.githubusercontent.com/33086594/168986344-9912dc7a-e8f2-4bf0-9930-032e4b4a8605.png">

**Comment by alexluigit** [comment]
现在应该好了。
另外你这个顶部标题怎么没内容? 是马赛克了吗?

**Comment by zrquan** [comment]
> 现在应该好了。 另外你这个顶部标题怎么没内容? 是马赛克了吗?

貌似和光标一样，通过 bookmark 打开目录会看不到标题，之前都没注意

**Comment by alexluigit** [comment]
你能简单发个重现步骤吗? 我没怎么用过自带的bookmark，谢谢

**Comment by zrquan** [comment]
可能是 counsel-bookmark 或者 doom-emacs 的问题？我的 elisp 目前还是 helloword 水平，不太会具体定位😂

![May-18-2022 17-20-52](https://user-images.githubusercontent.com/33086594/169005309-a79889ca-80b8-4a53-b30a-a7656080cd97.gif)

**Comment by alexluigit** [comment]
喔，ivy 的问题。等我写个补丁。consult-bookmark 没这毛病。

**Comment by alexluigit** [comment]
counsel-bookmark 应该好了, 你试试吧。

**Comment by zrquan** [comment]
标题已经没问题了，但 consult-bookmark 打开时光标还有点问题，貌似高亮的行和光标实际上不在同一行？

打开 dirvish 第一次移动会跳到不正确的行上：
![May-18-2022 19-59-04](https://user-images.githubusercontent.com/33086594/169033672-b2f5f941-1435-4643-a5f5-d54b14fdb4d7.gif)

比如上图 `(setq cursor-type 'box)` 之后其实 cursor 在第二行

**Comment by alexluigit** [comment]
还是一样的原因，我完全不理解 ivy 要在这里调用 `with-ivy-window`，这里出现的标题/行高亮都是这个造成的。我不太想在 dirvish 里 workaround，因为根源问题不在这里。

一个临时的解决办法

```emacs-lisp
(defadvice! counsel-bookmark-in-place ()
  "Forward to `bookmark-jump' or `bookmark-set' if bookmark doesn't exist."
  :override #'counsel-bookmark
  (require 'bookmark)
  (ivy-read "Create or jump to bookmark: "
            (bookmark-all-names)
            :history 'bookmark-history
            :action (lambda (x)
                      (cond ((and counsel-bookmark-avoid-dired
                                  (member x (bookmark-all-names))
                                  (file-directory-p (bookmark-location x)))
                             (let ((default-directory (bookmark-location x)))
                               (counsel-find-file)))
                            ((member x (bookmark-all-names))
                             (bookmark-jump x))
                            (t
                             (bookmark-set x))))
            :caller 'counsel-bookmark))
```

我后续看看有没有更好的办法解决。但我其实也并不能保证 ivy 里面会不会有其他地方导致什么问题。我的建议是从 ivy 全家桶换成 vertico +  consult (+ 其他) 这一套 (这也是doom 现在默认的选择)。ivy/counsel/swiper 里的很多问题在 vertico 这里根本不存在。

**Comment by zrquan** [comment]
了解，谢谢大佬
