### ISSUE TITLE
`(embark-act)` with `(dirvish)` cannot prompt a buffer.

### ISSUE THREAD

**Issue by Vonfry** [alexluigit/dirvish#46]
This is only appeared on `(dirvish)` (full frame) and not on `(dirvish-dirid)`.

***Reproduce***
1. `(dirvish)` in any dir
2. `(embark-act)` on any file.
3. ~Wait for several second, emacs is crashed.~

After restarting, emacs won't crash in such situation, but no embark buffer is prompted. By the way, embark-act can work.

***Version***
- Emacs: `GNU Emacs 28.1`
- dirvish: `dirvish-20220523.1338`
- embark: `embark-20220521.1736`

**Comment by alexluigit** [comment]
Thanks for reporting. I believe https://github.com/alexluigit/dirvish/commit/f50608facc468d2979ec654ed61f1e98c37f0ac2 fixed this.

**Comment by Vonfry** [comment]
Thanks.
