### ISSUE TITLE
incorrect sorting information in modelline?

### ISSUE THREAD

**Issue by fountainer** [alexluigit/dirvish#50]
调用`dired-sort-toggle-or-edit`函数，可以切换排序，不过modelline没有变化。
<img width="213" alt="image" src="https://user-images.githubusercontent.com/5546074/170810147-aaa467cc-af9f-40c1-9b4c-2a1d09fae0f7.png">
还有这个箭头，应该是向下还是向上，不太确定，这是苹果文件夹排序的箭头。
<img width="309" alt="image" src="https://user-images.githubusercontent.com/5546074/170810369-d75199fb-1807-4b8e-81ed-d9d6b4675443.png">

**Comment by alexluigit** [comment]
这里有写 https://github.com/alexluigit/dirvish/blob/main/CUSTOMIZING.org#example-config
```emacs-lisp 
;; Make sure to use the long name of flags when exists
;; eg. use "--almost-all" instead of "-A"
;; Otherwise some commands won't work properly
(setq dired-listing-switches
      "-l --almost-all --human-readable --time-style=long-iso --group-directories-first --no-group")
```

**Comment by alexluigit** [comment]
这里有写 https://github.com/alexluigit/dirvish/blob/main/CUSTOMIZING.org#example-config
```emacs-lisp 
;; Make sure to use the long name of flags when exists
;; eg. use "--almost-all" instead of "-A"
;; Otherwise some commands won't work properly
(setq dired-listing-switches
      "-l --almost-all --human-readable --time-style=long-iso --group-directories-first --no-group")
```

**Comment by fountainer** [comment]
加上好像还不行，modeline没有变化。

**Comment by alexluigit** [comment]
你确定你有用 `dirvish-quicksort` 覆盖 `dired-sort-toggle-or-edit` 吗? 那个示例里面有的

**Comment by fountainer** [comment]
这两句没有加上，不知道怎么拷贝掉了。加上就好了。
```emacs-lisp
 ([remap dired-sort-toggle-or-edit] . dirvish-quicksort)
 ([remap dired-do-redisplay] . dirvish-ls-switches-menu)
```

**Comment by alexluigit** [comment]
这两个功能在 dirvish-fd 的 结果页面也可以用。

**Comment by alexluigit** [comment]
fd 的 flag 可以用 `dirvish-fd-switches-menu` 调整，默认是 `? f`。如果你 fd 用的多，可以自己绑到别的按键。

**Comment by fountainer** [comment]
> 这两个功能在 dirvish-fd 的 结果页面也可以用。

我试了，很棒，内置`find-dired`好像就不能，我之前就是找这种工具。话说 Modification time 和 change time 什么区别？

**Comment by alexluigit** [comment]
mtime 是文件内容的改动, ctime 是指文件属性的改动，owner, group 之类的。

**Comment by fountainer** [comment]
> mtime 是文件内容的改动, ctime 是指文件属性的改动，owner, group 之类的。

谢谢，其他功能慢慢摸索，比如你说的`dirvish-fd-switches-menu`，好像不是variable, 是transient相关的，虽然也用magit, 但没有直接用过transient 。

**Comment by alexluigit** [comment]
就把它当个普通命令, 也可以 M-x 直接调用。

比如我在我的 Emacs 插件包目录演示一下: 
1. 以 test 为关键字搜索
2. 发现结果太多想进一步过滤
3. M-x dirvish-fd-switches-menu
4. 按 f (只显示文件结果，不要文件夹)
5. 按 -e, 输入想要显示的拓展名。
6. 按 -E，排除某些关键词。
7. 回车刷新

https://user-images.githubusercontent.com/16313743/170814774-98cc598d-6bc5-4fc3-9eea-21c98d6d4772.mp4

你在用 `dirvish-quicksort` 的时候，已经在用 transient 了，只是那个界面更简单，看不出来。

**Comment by fountainer** [comment]
果然好用，省的我查`fd`的参数，之前没有加载`dirvish-menu`, 以为`dirvish-fd-switches-menu`在`dirvish-fd`里面。
