### ISSUE TITLE
how to set opening .mp4 file with external program

### ISSUE THREAD

**Issue by wowhxj** [alexluigit/dirvish#51]
Firstly, thank you for the great package! It's really awesome. I've a question when I used dirvish as titled. Details is as following:

Environment:
- The latest version of dirvish installed today.
- Emacs 29
- MacOS 12.3.1

I've installed `mpv` via `brew` and can open `.mp4` files via `mpv xxxx.mp4` in command line.

When I open `.mp4` file via `find-file` or in dirvish window, it opened inside Emacs instead of `mpv`. See screenshot below.
Could you please help identify how to achieve this? Thanks a lot.
![图片](https://user-images.githubusercontent.com/78712451/170816145-c958ac71-abcc-4777-92fb-3a932f7ae559.png)

BTW, I've also tried to customize `dirvish-open-with-programs` as following:
```emacs-lisp
(defcustom dirvish-open-with-programs
  '(("video/" . ("mpv" "%f"))
    ("audio/" . ("mpv" "%f"))
    (("mp4")  . ("mpv" "%f"))
    (("html") . ("firefox" "%f")))
  "Association list of mimetype and external program for `find-file'.
Each element is of the form (TYPE . (CMD . ARGS)).  TYPE can be a
 string that stands for a mimetype or a list of file name
 extensions.  Once the TYPE is matched with FILENAME in
 `find-file', a subprocess according to CMD and its ARGS is
 issued to open the file outside of Emacs.  The special
 placeholder \"%f\" in the ARGS is replaced by the FILENAME at
 runtime.  Set it to nil disables this feature."
  :group 'dirvish
  :type '(alist :key-type ((choice string (repeat string)) :tag "File mimetype or extensions")
                :value-type ((repeat string) :tag "External command and args")))
```

Still not working, maybe I configured in a wrong way. (sorry that I'm not good at elisp)

**Comment by alexluigit** [comment]
I guess the reason is macOS failed to provide correct mimetypes to Emacs. I am planning to improve this in the near future.

For now, you can try this:
```emacs-lisp
(add-to-list 'mailcap-mime-extensions '(".mp4" . "video/mp4"))
```
Let me know if this works.

**Comment by wowhxj** [comment]
Seems that still not working. After setting this, the mp4 file is not opened inside Emacs. Instead, when I open via `find-file` nothing happened (no video window popup).
![图片](https://user-images.githubusercontent.com/78712451/170816727-784e01e4-e63f-4280-b4fc-daf2b85054bb.png)

I can open mp4 via `mpv` in eshell and it will popup a video window.
![图片](https://user-images.githubusercontent.com/78712451/170816834-91a0a3e4-ba89-413b-aa0b-7a9cfd0ffd41.png)

**Comment by wowhxj** [comment]
I also tried with `Emacs -Q` with following config:
```emacs-lisp
(add-to-list 'load-path "~/.emacs.d/straight/build/dirvish")
(require 'dirvish)
(add-to-list 'mailcap-mime-extensions '(".mp4" . "video/mp4"))
```

Same result.

**Comment by alexluigit** [comment]
```emacs-lisp
(defun dirvish-find-file-ad (fn filename &optional wildcard)
  "Advice for FN `find-file' and `find-file-other-window'.
FILENAME and WILDCARD are their args."
  (let* ((dv (dirvish-curr))
         (mime (or (mailcap-file-name-to-mime-type filename) ""))
         (ext (file-name-extension filename))
         (file (expand-file-name filename))
         (process-connection-type nil)
         (ex-cmd
          (and (not (file-remote-p file))
               (cl-loop
                for (type . (cmd . args)) in dirvish-open-with-programs
                thereis (and (executable-find cmd)
                             (or (and (listp type) (member ext type))
                                 (and (stringp type) (string-match type mime)))
                             (append (list cmd) args))))))
    (cond (ex-cmd
           (let ((default-directory dirvish-cache-dir))
             (and recentf-mode (add-to-list 'recentf-list file))
             (apply #'start-process "" nil
                    (cl-substitute (shell-quote-argument file) "%f" ex-cmd :test 'string=))))
          (dv
           (select-window (funcall (dv-find-file-window-fn dv)))
           (when-let ((dv (dirvish-prop :dv))) (dirvish-kill dv))
           (funcall fn filename wildcard))
          (t (funcall fn filename wildcard)))))
```
Just for testing, evaluate this and try open a video again, will the window popup?

**Comment by wowhxj** [comment]
After evaluated the code, the mp4 file is opened inside Emacs again.
![图片](https://user-images.githubusercontent.com/78712451/170817915-11d51960-00eb-4a7b-b190-91e8183811df.png)

**Comment by alexluigit** [comment]
What's in the preview window when you move the cursor to a .mp4 file?

**Comment by wowhxj** [comment]
![图片](https://user-images.githubusercontent.com/78712451/170818154-f7e360af-6007-4884-af2c-56f46e967f22.png)

**Comment by wowhxj** [comment]
![图片](https://user-images.githubusercontent.com/78712451/170818203-c4a15a40-cab3-415e-aa19-a49d5994e821.png)

**Comment by wowhxj** [comment]
I tried to change the program from `mpv` to `iina`. When I open mp4 file in dirvish, the IINA program will be launched without opening the mp4 file. Is it possible that `%f` is not passed to IINA program?
```emacs-lisp
(defcustom dirvish-open-with-programs
  '(("video/" . ("iina" "%f"))
    ("audio/" . ("iina" "%f"))
    (("mp4")  . ("iina" "%f"))
    (("html") . ("firefox" "%f")))
  "Association list of mimetype and external program for `find-file'.
Each element is of the form (TYPE . (CMD . ARGS)).  TYPE can be a
 string that stands for a mimetype or a list of file name
 extensions.  Once the TYPE is matched with FILENAME in
 `find-file', a subprocess according to CMD and its ARGS is
 issued to open the file outside of Emacs.  The special
 placeholder \"%f\" in the ARGS is replaced by the FILENAME at
 runtime.  Set it to nil disables this feature."
  :group 'dirvish
  :type '(alist :key-type ((choice string (repeat string)) :tag "File mimetype or extensions")
                :value-type ((repeat string) :tag "External command and args")))
```
![图片](https://user-images.githubusercontent.com/78712451/170818506-009055f1-5f13-42ef-b8cd-2c22915f5c55.png)

**Comment by alexluigit** [comment]
Try to open a mp4 file without Chinese characters in the path (such as "/User/user-name/123.mp4), is the problem persist?

**Comment by wowhxj** [comment]
I moved the file into `~/Downloads/` directory, and tried to open again, the problem disappeared.

**Comment by alexluigit** [comment]
I guess if you remove the "~" character in the filename, it should work fine.

**Comment by wowhxj** [comment]
I tested both `~` and Chinese directory name:
- ~/Downloads/中文目录/xxxx.mp4, not working.
- ~/Downlaods/test~dir/xxxx.mp4, notworking.
- ~/Downloads/xxxx.mp4, worked fine.

So is this problem an enhancement of dirvish shall add or an Emacs (macOS env) problem (which means cannot fix)?

**Comment by alexluigit** [comment]
> So is this problem an enhancement of dirvish shall add or an Emacs (macOS env) problem (which means cannot fix)?

It can be fixed of course, but I need more information to diagnose. Because it works for me no matter what type of characters are included in the filename.

```emacs-lisp
(defun dirvish-find-file-ad (fn filename &optional wildcard)
  "Advice for FN `find-file' and `find-file-other-window'.
FILENAME and WILDCARD are their args."
  (let* ((dv (dirvish-curr))
         (mime (or (mailcap-file-name-to-mime-type filename) ""))
         (ext (file-name-extension filename))
         (file (expand-file-name filename))
         (process-connection-type nil)
         (ex-cmd
          (and (not (file-remote-p file))
               (cl-loop
                for (type . (cmd . args)) in dirvish-open-with-programs
                thereis (and (executable-find cmd)
                             (or (and (listp type) (member ext type))
                                 (and (stringp type) (string-match type mime)))
                             (append (list cmd) args))))))
    (cond (ex-cmd
           (let ((default-directory dirvish-cache-dir))
             (and recentf-mode (add-to-list 'recentf-list file))
             (apply #'start-process "" nil "nohup"
                    (cl-substitute (shell-quote-argument file) "%f" ex-cmd :test 'string=))
             (message "comp cmd: %s" (cl-substitute (shell-quote-argument file) "%f" ex-cmd :test 'string=))
             (message "comp cmd w/o quoting: %s" (cl-substitute file "%f" ex-cmd :test 'string=))))
          (dv (select-window (funcall (dv-find-file-window-fn dv)))
           (when-let ((dv (dirvish-prop :dv))) (dirvish-kill dv))
           (funcall fn filename wildcard))
          (t (funcall fn filename wildcard)))))
```

Eval this and try to open a .mp4 in Dirvish and checkout *messages* buffer? Will these commands works in the command line or eshell?

**Comment by alexluigit** [comment]
说中文吧没事。这个问题不说非中文用户应该遇不到 :smirk_cat: :

**Comment by alexluigit** [comment]
我怀疑这个问题可能是在 (shell-quote-argument) 那里。你可以试试把那一行改成
```emacs-lisp
;; ...
             (apply #'start-process "" nil "nohup"
                    (cl-substitute file "%f" ex-cmd :test 'string=))
;; ...
```

**Comment by wowhxj** [comment]
> Eval this and try to open a .mp4 in Dirvish and checkout *messages* buffer. Will these commands works in the command line or eshell?

执行上面这段代码后message buffer里的是：
```
comp cmd: (iina /Users/randolph/Downloads/\中\文\目\录/694a57e993c79251c41cb52a4f39ca07.mp4)
comp cmd w/o quoting: (iina /Users/randolph/Downloads/中文目录/694a57e993c79251c41cb52a4f39ca07.mp4)
```

我用的是 zsh，在命令行里执行上面 message  buffer 里的 w/o quoting 的那串命令是可以成功的。

执行上面这个函数后，我打开 dirvish，然后按 ^ 回到 home 目录的过程中，Emacs会崩溃，试了几次都这样，我再看看。

**Comment by wowhxj** [comment]
> Eval this and try to open a .mp4 in Dirvish and checkout *messages* buffer. Will these commands works in the command line or eshell?

刚刚又试了一下，重新启动了Emacs -Q，执行上面的函数后，先通过 M-x dirvish，然后在中文目录里光标放到 mp4 文件上，按回车后无反应。在英文目录里按回车可以正常弹出窗口播放。

message buffer里打印如下：
```
dirvish-find-file-ad
comp cmd: (mpv /Users/randolph/Downloads/\中\文\目\录/694a57e993c79251c41cb52a4f39ca07.mp4)
comp cmd w/o quoting: (mpv /Users/randolph/Downloads/中文目录/694a57e993c79251c41cb52a4f39ca07.mp4)
```

**Comment by alexluigit** [comment]
那干脆这样 你把那两行换成
```emacs-lisp
;;;...
             (apply #'start-process "" nil "nohup"
                    (cl-substitute (format "'%s'" file) "%f" ex-cmd :test 'string=))
;;;...
```
看是不是可以了。估计 shell-quote-argument 这个函数跟 macOS 有点不对付。

**Comment by wowhxj** [comment]
> 

不行，改了之后，连原来不在中文目录里正常可以弹窗播放都不行了。然后中文目录里也没反应。

Message buffer里是这样：
```
comp cmd: (mpv /Users/randolph/Downloads/694a57e993c79251c41cb52a4f39ca07.mp4)
comp cmd w/o quoting: (mpv /Users/randolph/Downloads/694a57e993c79251c41cb52a4f39ca07.mp4)
...
comp cmd: (mpv /Users/randolph/Downloads/\中\文\目\录/694a57e993c79251c41cb52a4f39ca07.mp4)
comp cmd w/o quoting: (mpv /Users/randolph/Downloads/中文目录/694a57e993c79251c41cb52a4f39ca07.mp4)
```

**Comment by alexluigit** [comment]
命令行里把文件名两边加上单引号也打不开? macOS 好奇怪。

```emacs-lisp
             (apply #'start-process "" nil "nohup"
                    (cl-substitute (replace-regexp-in-string "[ '\"]" "\\\\\\&" file) "%f" ex-cmd :test 'string=))
```

这样可以了吗? 另外 message 那两行可以删了，跟要测的东西已经没关系了。

**Comment by alexluigit** [comment]
你更新看看吧。真是搞不懂为什么之前不加 shell-quote-argument 会打不开中文现在又可以了。

**Comment by wowhxj** [comment]
更新之后测试过了，中文目录，或者目录里含有波浪线符号的，都可以正常打开了。

感谢耐心诊断和快速修复！已经作为主力文件管理器使用了！
