### ISSUE TITLE
non-interactive find-file opens file in different directory

### ISSUE THREAD

**Issue by noctuid** [alexluigit/dirvish#53]
For example,
- Run `dirvish-dired`
- Change directory, e.g. to parent
- `(find-file "foo.org")`
- It will open foo.org in the child instead of the current directory dirvish is showing

This doesn't happen with `dired-jump`, for example.  Evil's `:e` is in my muscle memory for creating new files, and this usually creates new files in the wrong directory.

**Comment by alexluigit** [comment]
Thanks for reporting. Did https://github.com/alexluigit/dirvish/commit/f47331477af930a9759cadc9ade8cf81bc03497d fixed this?

**Comment by noctuid** [comment]
I works now.

> And FYI, I've remove the dirvish-dired command at cae89cc, this command can be replaced by dired-jump completely.

Thanks for the heads up.
