### ISSUE TITLE
`dirvish-dispatch` : `dirvish-other-buffer` not found

### ISSUE THREAD

**Issue by Dickby** [alexluigit/dirvish#54]
since it's obsolete it shouldn't be used in dirvish-dispatch i guess.
By the way how do you accomplish transient popups only being shown in one window.
On my emacs it spans across the width of the whole frame.

**Comment by alexluigit** [comment]
> since it's obsolete it shouldn't be used in dirvish-dispatch i guess.

Sorry for this, should have been fixed in the latest commit.

> By the way how do you accomplish transient popups only being shown in one window.

```emacs-lisp
(setq transient-display-buffer-action '(display-buffer-below-selected))
```

**Comment by Dickby** [comment]
Thanks!
