### ISSUE TITLE
`dirvish-toggle-fullscreen` doesn't work when opening with `dired-jump`

### ISSUE THREAD

**Issue by paladhammika** [alexluigit/dirvish#55]
Works fine with `dirvish` and `dirvish-split`. I get the follow response:
![image](https://user-images.githubusercontent.com/93992898/173233097-2bfbbb9c-8527-40dc-9a0a-c55b2220b641.png)

Please let me know what additional information would be needed.

**Comment by alexluigit** [comment]
You have to enable `dirivish-override-dired-mode` to use this command, since it only works for Dirvish sessions rather than regular dired buffers.

**Comment by paladhammika** [comment]
Oh I see. Needed to add :init above the line. Should pay more attention to your comments. Thanks for the response.
