### ISSUE TITLE
Persistence unhidden mode

### ISSUE THREAD

**Issue by jcguu95** [alexluigit/dirvish#63]
Thanks for writing dirvish :)

Currently, to show hidden files, a straightforward way is to invoke `dirvish-ls-switches-menu`. While we can use `M-RET` to apply the results to all dired buffers, it doesn't work for directories that are not "opened" yet. 

Could it be possible to have a persistent unhidden-mode? What are some entry points?

**Comment by alexluigit** [comment]
Hi @jcguu95 , thanks for reporting this.
After https://github.com/alexluigit/dirvish/commit/ef31960cf3f566bb5578b5c1bae45ece2939973b, M-RET would also apply those switches to the new dirvish buffers within the session.

> Could it be possible to have a persistent unhidden-mode?

C-u M-RET should do the job.

**Comment by jcguu95** [comment]
Fetched the last version and tested! While the setting persists with `C-u M-RET`, the effect doesn't take place. I have to go to `dirvish-ls-switches-menu` and hit `RET` again (without re-selecting the effect).

By the way, while it's nice to use the menu, sometimes I just want to hit a button and toggle hidden files. I know how to write easy elisp functions. What'd you suggest?

**Comment by alexluigit** [comment]
> with C-u M-RET, the effect doesn't take place

By C-u M-RET I mean hit this key chords inside of the menu. Is that what you did?

>  I just want to hit a button and toggle hidden file

For now the recommended way to achieve this is `dired-omit-mode`. You can customize `dired-omit-files` yourself. Maybe the `dirvish-emerge` extension can replace the functionality of `dired-omit-mode` in the near future ([ref](https://github.com/alexluigit/dirvish/discussions/58#discussioncomment-3049034)), I'll update the doc when this happens.

**Comment by jcguu95** [comment]
That's what I did. And the problem goes away in after I remove large chunks of old configs for dired. Thanks again for the wonderful package, and your help to make my experience smoother.
