### ISSUE TITLE
Dirvish refuse to open with error (wrong-type-argument integer-or-marker-p nil)

### ISSUE THREAD

**Issue by jcguu95** [alexluigit/dirvish#64]
I have received the following error many times when I invoke `M-x dirvish`. It does not open dirvish, which is quite confusing.. sometimes I have to relaunch emacs to make sure it works. Sometimes, it goes away after I fuddling around with other things..

The following is the message from my debugger.

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  apply(debug (error (wrong-type-argument integer-or-marker-p nil)))
  (let ((backtrace (doom-backtrace))) (setq num-nonmacro-input-events (1+ num-nonmacro-input-events)) (apply #'debug args))
  doom-debugger(error (wrong-type-argument integer-or-marker-p nil))
  dirvish-kill(#s(dirvish :path "~/" :layout (1 0.11 0.55) :last-fs-layout (1 0.11 0.55) :attributes nil :attribute-fns ((dirvish-hl-line-ov dirvish-attribute-hl-line-pred dirvish-attribute-hl-line-rd nil) (dirvish-symlink-target-ov dirvish-attribute-symlink-target-pred dirvish-attribute-symlink-target-rd nil)) :preview-dispatchers (text gif image video audio epub archive pdf-tools) :preview-fns (dirvish-tramp-preview-dp dirvish-disable-preview-dp dirvish-text-preview-dp dirvish-gif-preview-dp dirvish-image-preview-dp dirvish-video-preview-dp dirvish-audio-preview-dp dirvish-epub-preview-dp dirvish-archive-preview-dp dirvish-pdf-tools-preview-dp dirvish-default-preview-dp) :ls-switches "-AGhlv --group-directories-first --time-style=long..." :header-line-format ((:eval (let* ((dv (dirvish-prop :dv)) (buf (alist-get ... ... nil nil ...)) (scale 1) (win-width (floor ...)) (str-l "") (str-r "") (len-r 0)) (when (buffer-live-p buf) (setq str-l (format-mode-line ... nil nil buf)) (setq str-r (format-mode-line ... nil nil buf)) (setq len-r (string-width str-r))) (concat (dirvish--bar-image (dv-layout dv) t) (if (< ... win-width) str-l (let ... ...)) (propertize " " 'display `...) str-r)))) :mode-line-format ((:eval (let* ((dv (dirvish-prop :dv)) (buf (alist-get ... ... nil nil ...)) (scale 1) (win-width (floor ...)) (str-l "") (str-r "") (len-r 0)) (when (buffer-live-p buf) (setq str-l (format-mode-line ... nil nil buf)) (setq str-r (format-mode-line ... nil nil buf)) (setq len-r (string-width str-r))) (concat (dirvish--bar-image (dv-layout dv) nil) (if (< ... win-width) str-l (let ... ...)) (propertize " " 'display `...) str-r)))) :root-window-fn #f(compiled-function (dv) #<bytecode 0x328586aaf5ab20b>) :root-window #<window 439 on ~<3>> :on-file-open dirvish-on-file-open :quit-window-fn ignore :scopes nil :preview-buffers nil :preview-window nil :name G622 :window-conf #<window-configuration> :roots nil :parents nil :index-dir ""))
  dirvish(nil)
  #<subr funcall-interactively>(dirvish nil)
  apply(#<subr funcall-interactively> (dirvish nil))
  funcall-interactively(dirvish nil)
  #<subr call-interactively>(dirvish nil nil)
  apply(#<subr call-interactively> (dirvish nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> dirvish nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (dirvish nil nil))
  call-interactively(dirvish nil nil)
  command-execute(dirvish)
```

**Comment by jcguu95** [comment]
A quick guess of the problem is in the following code

``` 
(defun dirvish-new ;; ..
;; ..
         (dirvish-find-file (expand-file-name (file-name-directory path))))
;; ..
```

While `(expand-file-name (file-name-directory "~/"))` returns correctly, `(expand-file-name (file-name-directory "~"))` fails and invokes an error. On the other hand, `#'dirvish` calls `default-directory` which might sometimes be in the format unexpected by `#'file-name-directory` (e.g. `"~"` as above).

**Comment by alexluigit** [comment]
I can reproduce this when `M-x dirvish` within an fullscreen session, the error occurred when dirvish tries to kill the newly created session. Please let me know if 73761c5d42590b2d2d2f76468a0b8f6fe12bb3e2 fixed this.  If the commit failed to fix this, more detailed reproduce steps are needed. Thanks.

**Comment by jcguu95** [comment]
Hi. I've been testing for the past two days. Indeed the same issue seems to go away after the commit you mentioned. However, the error seems to be replaced by the message `"Dirvish: using existed session"`. This sometimes happened when dirvish isn't the current buffer.. which still blocks the user to access to dirvish whenever they want to in practice. - Hopefully this helps, and thanks again :)

**Comment by alexluigit** [comment]
Thanks for the feedback. If this error message show up at a non-dirvish buffer, it means you had a previous dirvish session not being closed cleanly.  `quit-window` (`q` by default) is the only way to close a full-screen dirvish session. In other words, if you try to hide/unhide a full-screen session in any ways, you probably will run into this error. So how did you quit the dirvish session? Are you using packages like winner-mode/persp/perspective or alike to help you manage the window layout?

**Comment by jcguu95** [comment]
I didn't quit it, but just jump to another buffer, say, my org-agenda.

**Comment by alexluigit** [comment]
After 0ccdb1ab963d87c2785fa9f90a8d8642e79c38b7, users should be able to reuse the fullscreen session within the frame. But I'm not sure if this commit would work for you, because I'm not able to repro what you described here in `emacs -q`. If this commit doesn't fix the issue for you, I believe we need more details to diagnose the issue, like minimal repro steps with `emacs -q`.
