### ISSUE TITLE
Dirvish filter misbehaves after directory content change

### ISSUE THREAD

**Issue by jcguu95** [alexluigit/dirvish#65]
Normally, I kept the hidden files hidden. However, this behavior breaks once the content of the current directory changes.

To reproduce, open dirvish at the home directory. In the command line, add a new file by `touch ~/a`. Then as dirvish updates the content of the home directory, it also shows the hidden files too.

**Comment by alexluigit** [comment]
I'm not able to reproduce this on `emacs -q` through `dired-create-empty-file` or command line. Can you provide a `emacs -q` recipe to reproduce this?

**Comment by jcguu95** [comment]
I think something weird in my config was faulty for that. Sorry for the issue.
