### ISSUE TITLE
Dirvish has bad interaction with evil cursor in other buffers

### ISSUE THREAD

**Issue by aikrahguzar** [alexluigit/dirvish#66]
Specifically the sequence of steps is this:
1) `M-x dirvish-override-dired-mode RET`. 
2) `M-x dired-jump RET` to open a dirvish buffer.
3) `M-x dired-omit-mode RET` to enable `dired-omit-mode`.
4) `M-x kill-current-buffer RET` to kill the dirvish buffer.
5) This brings me back to the original buffer. Now press `i` to enter insert-mode. The buffer is now in insert mode but the cursor remains the bar cursor of the normal mode.

This is with default configuration of `dirvish`. I haven't tried to reproduce it in `emacs -Q` since setting up evil there is beyond me.

I don't know why `dired-omit-mode` causes this issue and it is very weird interaction but the problem is more general and I have encountered it in other scenarios too but this is the simplest reliably reproducible one.

**Comment by alexluigit** [comment]
What commit are you using? Did ef52c91862f3bbb92b55337eaf180fe31589555b fixed this? With the latest version I'm not able to reproduce in both `emacs -q` and doom-emacs.

**Comment by aikrahguzar** [comment]
> What commit are you using? Did [ef52c91](https://github.com/alexluigit/dirvish/commit/ef52c91862f3bbb92b55337eaf180fe31589555b) fixed this? With the latest version I'm not able to reproduce in both `emacs -q` and doom-emacs.

I am on the latest commit. The issue happen for me completely reproducibly but the problem wasn't `dired-omit-mode` it was actually something else. After a lot of head scratching I realized that the problem happens whenever I  am not prompted to confirm when I kill the buffer. Using minibuffer fixed the issue so it led me to believe that it was something to do various `window-*-change-functions` which led me to `dirvish-reclaim` which in turn led me to `dirvish-advice-alist` and removing the entry for evil in it fixes the issue for me.

**Comment by aikrahguzar** [comment]
A semi-related question: why does `dired-jump` revert the buffer? Reverting can take sometime especially with larges buffer and `dirvish-emerge-mode` turned on.

**Comment by alexluigit** [comment]
> whenever I am not prompted to confirm when I kill the buffer

I have `dired-clean-confirm-killing-deleted-buffers` set to nil and it seems that dired never prompts me for confirmation.

> why does dired-jump revert the buffer? 

If you mean `dired-jump` after `dirvish-override-dired-mode`, then it does not revert the buffer. Actually Dirvish only revert buffers when user explicitly calling `revert-buffer` or commands that require a buffer reverting such as `dirvish-quicksort`. If you are experiencing unexpected buffer reverting, you should check out your config related to auto-revert or something like that.

**Comment by aikrahguzar** [comment]
> I have `dired-clean-confirm-killing-deleted-buffers` set to nil and it seems that dired never prompts me for confirmation.

For me that doesn't help, its documentation just says that `dired` will not not prompt before killing a buffer for a directory with deleted files. There are no deleted files here, just that the buffer appears modified due to text properties. There is probably another variable I can set for that.

> If you mean `dired-jump` after `dirvish-override-dired-mode`, then it does not revert the buffer. Actually Dirvish only revert buffers when user explicitly calling `revert-buffer` or commands that require a buffer reverting such as `dirvish-quicksort`. If you are experiencing unexpected buffer reverting, you should check out your config related to auto-revert or something like that.

I did mean that scenario, I do have auto revert but should only trigger when the directory has been modified and that is the case with dired but after  with dirvish I frequently see `Reverting buffer buffer-name` in my messages buffer and the buffer flickers. I will try to isolate the cause of it.

I see that you reverted the commit setting `evil-normal-mode-cursor`. Why not remove the advice for evil from the `evil-advice-alist`? That seems to work fine for me and setting the normal mode cursor buffer-locally should be all that is needed? 

And why are these advices applied on every `dirvish-reclaim` which is in a lot of hooks? I think running them once on `dirvish-override-dired-mode` or even just when loading `dirvish.el` should be enough? I think most of them effect on `dirvish-mode` buffers and let others pass through? And if you just set them just once, it is also easier to remove them and deal with the resulting breakage that happens only once in the config which makes it easier to tinker with dirvish.

**Comment by alexluigit** [comment]
> That seems to work fine for me and setting the normal mode cursor buffer-locally should be all that is needed?

I thought the same. If I just set the `evil-normal-mode-cursor`, it works fine for me in doom-emacs, but in `emacs -q`, the cursor is still showing and blinking. I'm confused about how evil handles the cursor refresh. 

> And why are these advices applied on every dirvish-reclaim which is in a lot of hooks? 

Because `dirvish-override-dired-mode` is not a requirement to use this package. This design is for users who want to use dirvish but don't want to enable `dirvish-override-dired-mode`. But as of now (v1.8) I do feel that override dired is a necessary thing to do for dirvish users. So I'll move these advices to `dirvish-override-dired-mode` as you suggested. Thanks for mentioning this.

**Comment by aikrahguzar** [comment]
> I thought the same. If I just set the `evil-normal-mode-cursor`, it works fine for me in doom-emacs, but in `emacs -q`, the cursor is still showing and blinking. I'm confused about how evil handles the cursor refresh.

I think this is due to the use of `bound-and-true-p` in

```elisp
(when (bound-and-true-p evil-normal-state-cursor)
    (setq-local evil-normal-state-cursor '(bar . 0)))
```
The default value of `evil-normal-state-cursor` is `nil` so the `setq-local` part is never executed unless `evil-normal-state-cursor` has been set which I guess doom does at some point before `dirvish-setup` is run.

Changing it to,
```elisp
 (when (boundp evil-normal-state-cursor)
    (setq-local evil-normal-state-cursor '(bar . 0)))
```
should work.

> Because `dirvish-override-dired-mode` is not a requirement to use this package. This design is for users who want to use dirvish but don't want to enable `dirvish-override-dired-mode`. But as of now (v1.8) I do feel that override dired is a necessary thing to do for dirvish users. So I'll move these advices to `dirvish-override-dired-mode` as you suggested. Thanks for mentioning this.

The only advices that `dirvish-reclaim` removes are in
```elisp
(dirvish--remove-advices
            (and dirvish-override-dired-mode '(dired find-dired)))
```
while it unconditionally adds them for all the packages. This suggests to me that even if you don't go with adding and removing advices on `dirvish-override-dired-mode`, `dirvish-reclaim` can be changed to add advices only for `dired` and `find-dired` and advices for all other packages can be added at the top level statement in `dirvish.el` so they are added when `dirvish` is loaded.

Though I think adding and removing them on `dirvish-override-dired-mode` would be better.

**Comment by alexluigit** [comment]
> Changing it to,
> ```
> (when (boundp evil-normal-state-cursor)
>    (setq-local evil-normal-state-cursor '(bar . 0)))
>```
> should work.

Thanks a lot for this. I don't use `evil-mode` myself so debugging evil stuff is always painful to me. 

> Though I think adding and removing them on dirvish-override-dired-mode would be better.

It is something I always wanted to do. What prevented me from doing this is that these packages are not necessarily ready for us to `require` at the time when the user's dirvish config is being loaded, since people use different tricks for lazy loading. To avoid, I have to use `with-eval-after-load`, then package-lint.el gives me a warning saying that [`with-eval-after-load' is for use in configurations, and should rarely be used in packages.](https://github.com/alexluigit/dirvish/runs/7163235122?check_suite_focus=true#step:5:20). Anyways, I decided to live with it, after all `with-eval-after-load` is widely used in those popular packages.

**Comment by aikrahguzar** [comment]
> Thanks a lot for this. I don't use `evil-mode` myself so debugging evil stuff is always painful to me.

Happy to help! You are doing great work here. And even though I really like evil, setting it up would be a real hassle without doom. It is probably the only part of emacs that I haven't tried to tinker with yet.

> It is something I always wanted to do. What prevented me from doing this is that these packages are not necessarily ready for us to `require` at the time when the user's dirvish config is being loaded, since people use different tricks for lazy loading. To avoid, I have to use `with-eval-after-load`, then package-lint.el gives me a warning saying that [`with-eval-after-load` is for use in configurations, and should rarely be used in packages](https://github.com/alexluigit/dirvish/runs/7163235122?check_suite_focus=true#step:5:20). Anyways, I decided to live with it, after all `with-eval-after-load` is widely used in those popular packages.

I don't think `with-eval-after-load` is needed. I was under the impression that you can advice a function before it is defined/loaded/bound and this seems to confirm it https://emacs.stackexchange.com/questions/37955/adding-advice-to-an-autoloaded-function though there is better resource to explain it.

You can even use other functions/variables from the package containing the functions you are advising. In that case you would just need to declare these function/variables to byte compiler. Have you run into any problems adding advice without `with-eval-after-load`? Just advising won't load anything.

**Comment by alexluigit** [comment]
> you can advice a function before it is defined/loaded/bound

That's a news to me, thank you! I've seen people require a package before advising functions in it from place to place, so I thought advising should happen after definition.  

> Have you run into any problems adding advice without with-eval-after-load?

If my memory serves me, I haven't even tried this before. And I removed the `with-eval-after-load` just now, it works like a charm, doing this also cuts down my `emacs-init-time` a little bit. Great tip, thanks again!

**Comment by aikrahguzar** [comment]
> That's a news to me, thank you! I've seen people require a package before advising functions in it from place to place, so I thought advising should happen after definition.

I have seen that too and that kind of makes sense because it seem natural of think of advice as something attached to a function. But in reality it is something attached to the symbol. So, it is just another symbol-property which comes into play when the symbols function definition (another property of the symbol) is used but is not in anyway related to the function definition itself. 

For example if evaluate `(get 'set-window-buffer 'ad-advice-info)`, I obtain,
```elisp
((active . t)
 (advicefunname . ad-Advice-set-window-buffer)
 (before
  (evil nil t
        (advice lambda nil "Initialize Evil in the displayed buffer."
                (when evil-mode
                  (when
                      (get-buffer
                       (ad-get-arg 1))
                    (with-current-buffer
                        (ad-get-arg 1)
                      (unless evil-local-mode
                        (evil-local-mode 1))))))))
 (cache #f(compiled-function
           (ad--addoit-function window buffer-or-name &optional keep-margins)
           #<bytecode 0x18a0f260834406c9>)
         (evil)
         nil nil subr2
         (window buffer-or-name &optional keep-margins)
         nil))
```
