### ISSUE TITLE
Unexpected behavior for dirvish-narrow

### ISSUE THREAD

**Issue by fountainer** [alexluigit/dirvish#67]
Run `dirvish-narrow` and input `org` in repo directory. Then, Press `U t` to select all the items related to narrowed items.
<img width="522" alt="org-appear" src="https://user-images.githubusercontent.com/5546074/176988950-d3181d8c-233b-430c-a7c4-36958dfafa5d.png">
There are also some minor issues.  The "forge" item line displays detailed information. Some icons are also missing.

Then run `revert-buffer`. All the items are selected as shown below:
<img width="814" alt="LaTeX-auto-activating-snippets" src="https://user-images.githubusercontent.com/5546074/176989027-045797bf-7252-45db-8a1f-572e1959a615.png">

What I expected is that only items related to "org" are selected.

**Comment by alexluigit** [comment]
Thanks for your feedback. Please try out b0c16a5f5d619783b32f00d4723480b211578237.
This is a new extension so bugs are expected. A known issue is that this doesn't work well with dirvish-subtree for now. I'll see if I can fix the issue in the near future.

**Comment by fountainer** [comment]
It works as expected. Thanks.
