### ISSUE TITLE
scroll-other-window not work

### ISSUE THREAD

**Issue by 404cn** [alexluigit/dirvish#7]
Just run `dirvish` and press `C-M-v`, get `end of buffer`.

And I can not run it with `emacs -Q` because it says no dash installed (install dicvish via straight).

**Comment by alexluigit** [comment]
Hi @404cn , thanks for reporting.
Please check if the latest commit solves the window scrolling issue.

> And I can not run it with `emacs -Q` because it says no dash installed (install dicvish via straight).

I can not reproduce this on my machine, I guess this is caused by other packages in your configuration since dirvish does *not* require dash (it only requires Emacs 27.1).

**Comment by 404cn** [comment]
> Please check if the latest commit solves the window scrolling issue.

Thanks it works!
