### ISSUE TITLE
Dirvish opens empty Dirvish Temp buffer when using `counsel-find-file`

### ISSUE THREAD

**Issue by Aaronzinhoo** [alexluigit/dirvish#70]
I just started using `Dirvish` and love how much more convenient it is for basically everything! One thing I did notice is that when I used `counsel-find-file` though is I get an empty Dirvish Temp buffer that pops up. When I am in Dirvish mode (3 panes open) though this does not occur. Is this expected or is there some setting to suppress the temp buffer from appearing?

**Comment by alexluigit** [comment]
> when I used `counsel-find-file` though is I get an empty Dirvish Temp buffer that pops up

If you've enabled `dirvish-peek-mode`, then this is expected. If everything goes fine, as you narrowing the candidates in the minibuffer, the preview of the file under cursor will show up in that temp buffer ([demo](https://github.com/alexluigit/dirvish/blob/main/EXTENSIONS.org#minibuffer-file-preview-dirvish-peekel)). If you don't want this, just turn of `dirvish-peek-mode`.

**Comment by Aaronzinhoo** [comment]
What I get when I use `counsel-find` is this 

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/26849064/178617214-807d6ded-c16e-4910-981c-c6a36dca5f57.png">

**Comment by alexluigit** [comment]
Anything interesting in *backtrace* or _*messages*_ buffer after `toggle-debug-on-error`? A minimal configuration to reproduce this would be helpful.

**Comment by Aaronzinhoo** [comment]
That was it! I didn't realize the backend variable for peek mode! I really am enjoying how similar dirvish is to dired but without the difficulty of learning dired.

**Comment by alexluigit** [comment]
I removed that option at 6ecf152b5374f1617fad1c0959d1a36311086161 since it is unreliable. Now it should work OOTB.

```quote
Setting the candidate retriever function at Emacs startup is not reliable since
user might configure dirvish before loading their choice of completion
framework (vertico, ivy, etc.). For that I removed the `dirvish-peek-backend`
user option and let dirvish get the cand-retriever at runtime.  If the users
want to use their custom candidate-retriever, the new option
`dirvish-peek-candidate-fetcher` is provided for that job.
```
