### ISSUE TITLE
Down key often moves more than one line

### ISSUE THREAD

**Issue by muihlinn** [alexluigit/dirvish#77]
I have a weird issue which happens navigating trough directory contents.

When pressing `<down`>, `n`,  or `C-n` sometimes it moves more than a line.
- Keys are bound to `dired-next-line`
- It doesn't seems to happen with `emacs -Q` loading only dirvish.el and dirvish-media.el
- Seems to happen on specific files of any kind, but unpredictably until it happens (as far as I can go)
- it doesn't happen in dired
- it doesn't affect to `<up>` in same files, or any file.
- sorting doesn't seem to have any effect on this

Using:
- emacs 28.1.50
- latest elpa dirvish (although it has been happening for a while) 

my configuration either dirvish or dired is pretty minimal, this are the only things that may have something to do with it.  
 
```lisp
(so-long-threshold 3048)
(dirvish-attributes '(subtree-state all-the-icons file-size))
```
Any clue to debug this?

**Comment by alexluigit** [comment]
Does the filename includes any non-ASCII characters (such as characters in European languages other than English)?   Will remove `file-size` from `dirvish-attributes` make any differences?

**Comment by alexluigit** [comment]
Please leave this issue open, I'll see what I can do to reproduce and fix this.

**Comment by alexluigit** [comment]
Please let me know if ec051a01b11ced661afd8b004fd5c161a811251e fixed this. Thanks.

**Comment by muihlinn** [comment]
Looks fixed

**Comment by mikezackles** [comment]
I just ran into this using dirvish installed from git `main`. Removing `file-size` works around the problem.

**Comment by mikezackles** [comment]
![dirvish-bug](https://github.com/alexluigit/dirvish/assets/77851/34c2413e-5e28-4560-bef9-cb2e596fead2)
In the pictured scenario, dirvish jumps from `completion_signatures.hpp` to `connect.hpp`, skipping `concepts.hpp`.

**Comment by ghost** [comment]
Excuse me? I met this behavior with dirvish-20250504.807 again. 

Expected: C-n moves 1 line
Actual: C-n moves 2 lines
Workaround: emacs-feature-igc 31.0.50 on WSL2

Mainly my configuration leads to this behavior maybe , and I solve it by advice finally.

Here is my solution about it from DeepSeek V3.
`(with-eval-after-load 'dirvish
  (advice-add 'dired-next-line :override
              (lambda (&optional arg)
                (next-line (or arg 1)))))`

It is a so awesome plugin in my daily workflow. Thanks for developing it!

**Comment by Czcfsdx** [comment]
Same issus with dirvish-20250504.807
But this time I remove `git-msg` from `dirvish-attributes` which seems to solve the issue

**Comment by knazarov** [comment]
I think I narrowed this down. I have same issue, and it seems to be related to the visual length of the ellipsis. I use Iosevka font, and the `…` that is replacing the part of the git commit message that doesn't fit into the column is 2-characters wide.

This is how I worked this around by replacing ellipsis with an underscore:

```
(dirvish-define-attribute git-msg
  "Display short git log."
  :when (and (eq (dirvish-prop :vc-backend) 'Git) (not (dirvish-prop :remote)))
  :setup (dirvish-prop :gm-chop
           (seq-reduce (lambda (acc i) (cl-incf acc (nth 2 i)))
                       (dirvish-prop :attrs) 0))
  (let* ((msg-raw (dirvish-attribute-cache f-name :git-msg))
         (msg (if (>= (length msg-raw) 1) (substring msg-raw 0 -1) ""))
         (face (or hl-face 'dirvish-git-commit-message-face))
         (chop (dirvish-prop :gm-chop)) (mlen (length msg)) (stop t)
         (limit (- (floor (* (if (< w-width 70) 0.48 0.6) w-width)) chop))
         (count 0) (whole (concat " " msg (make-string w-width ?\ ))) str len)
    (cond ((or (not msg-raw) (< w-width 30)) (setq str ""))
          ((and (>= w-width 30) (< w-width 50)) (setq str (propertize " _  ")))
          (t (setq str "" stop (<= limit 0))))
    (while (not stop) ; prevent multibyte string taking too much space
      (setq str (substring whole 0 count))
      (if (>= (- limit (string-width str)) 1)
          (cl-incf count)
        (setq str (concat str (if (> count mlen) "  " "_ ")) stop t)))
    (add-face-text-property 0 (setq len (length str)) face t str)
    (add-text-properties 0 len `(help-echo ,msg) str)
    `(right . ,str)))
```

But I doubt this is a good long-term fix. Something in the widget rendering is not taking this into account.

**Comment by gekoke** [comment]
I can confirm exactly the same symptoms as @knazarov. The behavior is only happening when there is an ellipsis in the `git-msg` - crazy how you figured that out.

**Comment by knazarov** [comment]
I decided to create a new issue #356
