### ISSUE TITLE
dired-do-copy with two dirvish-dired windows open doesn't behave like dired windows

### ISSUE THREAD

**Issue by chm-von-tla** [alexluigit/dirvish#8]
When you have two dired windows open, mark a file/directory and run `dired-do-copy` the minibuffer prompt defaults to the directory of the other open window (the inactive one). 

However when you try to do the same thing with dirvish-dired windows, the prompt defaults to the directory of the current window.

The same behavior can also be seen with similar commands to `dired-do-copy` like `dired-do-rename` or `dired-rsync`

**Comment by alexluigit** [comment]
Hi Charis, Thanks for your report. Is https://github.com/alexluigit/dirvish/commit/6b4b7fc6e0aa875ef8e5a79f8364c87b558a6e60 fixed this issue for you?

**Comment by chm-von-tla** [comment]
Sadly I couldn't get it to work. It threw some errors. I didn't try it with a clean config though so maybe the problem is on my part. Sadly I don't have the time to try to debug this at present

**Comment by alexluigit** [comment]
Could you paste the backtrace of the error (just M-x toggle-debug-on-error) ?

Here is a simple test to tell if the dwim-target mechanism works correctly.

```shell
cd /path/to/dirvish
emacs -q -L . -l dirvish.el --eval '(progn (setq dired-dwim-target t) (split-window-right) (dirvish-dired) (other-window 1) (dirvish-dired "/"))'
```

After the Emacs window showed up, press "C" to see the guessed target. It works fine on my machine.

**Comment by chm-von-tla** [comment]
Works fine on a clean config. The problem with the errors was indeed on my side. Sorry for wasting your time with my previous comment.
