### ISSUE TITLE
[Feature Request] Reuse Emacs bookmarks for dirvish-bookmark

### ISSUE THREAD

**Issue by karthink** [alexluigit/dirvish#81]
**Is your feature request related to a problem? Please describe.**
The `dirvish-bookmark` feature requires bookmark candidates to be explicitly defined. As it stands this is an isolated feature that's only available when using `dirvish`. This can be better integrated with Emacs' built-in features.

**Describe the solution you'd like**
Emacs' excellent bookmark system is already available system-wide and can be made available to `dirvish-bookmark` with minimal tweaking. Here's a rough draft:

```emacs-lisp
;; Collect Emacs bookmarks that are directories.
(setq dirvish-bookmark-entries
      (cl-loop initially (bookmark-maybe-load-default-file)
               for cand in 
               (thread-last
                 bookmark-alist
                 (cl-remove-if (lambda (cand) (bookmark-get-handler cand)))
                 (cl-remove-if-not
                  (lambda (cand)
                    (let ((bm (bookmark-get-bookmark-record cand)))
                      (when-let ((file (alist-get 'filename bm)))
                        (if (file-remote-p file)
                            (string-suffix-p "/" file)
                          (file-directory-p file)))))))
               for index from 0 to 9
               collect (list (number-to-string index)
                             (alist-get 'filename (cdr cand))
                             (car cand))))

;; Create transient menu with these bookmarks
(eval
 `(transient-define-prefix dirvish-bookmark-jump ()
   "Jump to Dirvish bookmarks."
   [:description
    (lambda () (dirvish--format-menu-heading "Go to Directory: "))
    :pad-keys t
    ,@(cl-loop
       for (key path desc) in dirvish-bookmark-entries
       collect
       (list key
             desc
             `(lambda ()
                (interactive)
                (dired-jump current-prefix-arg ,path))))]))
```

I can now see my first few Emacs bookmarks (that are directories) when using `dirvish-bookmark-jump`:
![2022-07-18-180238_1051x433_scrot](https://user-images.githubusercontent.com/8607532/179515158-efecb04f-15f1-4014-bb04-ae252ce82856.png)

**Describe alternatives you've considered**
The Transient menu approach to this doesn't scale once the user has more than a dozen or so directory bookmarks. So this could just be a call to `completing-read` with a custom format spec that allows filtering by both the bookmark name and path.

**Additional context**
Emacs' bookmarks system is really useful for integrating workflows and packages, so I thought it makes sense to integrate `dirvish-bookmark` with it.

Also, I don't think you need the width calculation for the transient menu any more because of the `:pad-keys` key in `transient-define-prefix`.

**Comment by alexluigit** [comment]
`dirvish-quick-access` looks good to me, thanks for your advice!

**Comment by karthink** [comment]
Thanks for the clarification. The "places" section of GUI file explorers suffer from the same bookmarks scaling problem, but it makes sense to have a few fixed locations. Renaming it to `dirvish-quick-*` sounds good too.

> A known issue in dirvish for now is that when the user invoke the `bookmark-jump` command, the opened session is not reused, but apart from that, I don't see any obstacles for dirvish to support these commands or packages directly. What do you think?

I didn't follow what you mean by supporting these commands or packages directly. What does it mean for dirvish to "support" `consult-bookmark`, for instance?

**Comment by alexluigit** [comment]
By support I mean using them without any issue, the opened dired buffer should be overrided by dirvish correctly.  In the context of `consult-bookmark` this also relates to override the preview buffer it provides.  I believe they are not fully supported for now because of known issues like this one: https://github.com/alexluigit/dirvish/issues/88

> So this could just be a call to `completing-read` with a custom format spec that allows filtering by both the bookmark name and path

Since dirvish won't touch those bookmarks, packages like `consult` or `burly` would be the right candidates to take care of this.

**Comment by karthink** [comment]
I see what you mean by "support" these packages. That makes sense. I tried `consult-bookmark` from a dirvish buffer and I do see #88 too.
