### ISSUE TITLE
Dispatcher not bound by default

### ISSUE THREAD

**Issue by alphapapa** [alexluigit/dirvish#82]
It seems like the dispatcher should be bound by default in Dirvish buffers, e.g. `?` in a magit-status buffer shows the Magit dispatcher.  Having to use `M-x dirvish-dispatch RET` to get it almost defeats its purpose.  :)

**Comment by alexluigit** [comment]
Thanks for the suggestion. I might be too conservative about providing default keybindings. I'll map it to the `?` key.
