### ISSUE TITLE
[Feature Request] missing install dependencies

### ISSUE THREAD

**Issue by hammerandtongs** [alexluigit/dirvish#85]
Please put the install dependencies in a prominent spot in the landing page.

For debian its -

`apt install poppler-utils ffmpegthumbnailer mediainfo`

I can't find epub-thumbnailer in debian, and I'm not sure which script you are referring to from a web search -

https://github.com/marianosimone/epub-thumbnailer/blob/master/src/epub-thumbnailer.py

zipinfo and tar are obvious but maybe good to add.

The thumbnailer issues might suggest this is a larger problem for emacs and could use a standalone package.

**Comment by alexluigit** [comment]
> Please put the install dependencies in a prominent spot in the landing page.

Thanks for the advice, I'll put dependencies in README

> I can't find epub-thumbnailer in debian, and I'm not sure which script you are referring to

The link you posted here is the right repo. But since this package might be hard to obtain on some platforms, I'll remove `epub` from the `dirvish-preview-dispatcher`, thanks for reporting this.

> The thumbnailer issues might suggest this is a larger problem for emacs and could use a standalone package.

I'm sorry but I don't understand what's the "larger problem" you are referring to? What do you mean by "use a standalone package"?

**Comment by hammerandtongs** [comment]
> > Please put the install dependencies in a prominent spot in the landing page.
> 
> Thanks for the advice, I'll put dependencies in README
> 
> > I can't find epub-thumbnailer in debian, and I'm not sure which script you are referring to
> 
> The link you posted here is the right repo. But since this package might be hard to obtain on some platforms, I'll remove `epub` from the `dirvish-preview-dispatcher`, thanks for reporting this.

I think that would be an unfortunate choice. Maybe explicitly direct people to the github readme in the emacs log?

"""
epub-thumbnailer can be simply obtained from -

https://raw.githubusercontent.com/marianosimone/epub-thumbnailer/master/src/epub-thumbnailer.py

Download this file into your bin path, remove the .py from the filename and chmod 700 it into an executable.

Or go through the documented install path in it's github README. The python libraries used are usually installed already so this is probably unneeded.
"""

This worked well for me and I really like having the epub thumbnails for sure.

> > The thumbnailer issues might suggest this is a larger problem for emacs and could use a standalone package.
> 
> I'm sorry but I don't understand what's the "larger problem" you are referring to? What do you mean by "use a standalone package"?

I really just meant that other emacs packages need a good set of thumbnails too and maybe a general package would allow it to all get polished at the same time.

**Comment by hammerandtongs** [comment]
> > Please put the install dependencies in a prominent spot in the landing page.
> 
> Thanks for the advice, I'll put dependencies in README
> 
> > I can't find epub-thumbnailer in debian, and I'm not sure which script you are referring to
> 
> The link you posted here is the right repo. But since this package might be hard to obtain on some platforms, I'll remove `epub` from the `dirvish-preview-dispatcher`, thanks for reporting this.

I think that would be an unfortunate choice. Maybe explicitly direct people to the github readme in the emacs log?

"""
epub-thumbnailer can be simply obtained from -

https://raw.githubusercontent.com/marianosimone/epub-thumbnailer/master/src/epub-thumbnailer.py

Download this file into your bin path, remove the .py from the filename and chmod 700 it into an executable.

Or go through the documented install path in it's github README. The python libraries used are usually installed already so this is probably unneeded.
"""

This worked well for me and I really like having the epub thumbnails for sure.

> > The thumbnailer issues might suggest this is a larger problem for emacs and could use a standalone package.
> 
> I'm sorry but I don't understand what's the "larger problem" you are referring to? What do you mean by "use a standalone package"?

I really just meant that other emacs packages need a good set of thumbnails too and maybe a general package would allow it to all get polished at the same time.

**Comment by alexluigit** [comment]
> Maybe explicitly direct people to the github readme in the emacs log?

I added a config example for this [here](https://github.com/alexluigit/dirvish/blob/main/CUSTOMIZING.org#sample-3-remove-the-epub-preview-method)

The installation guide has been put in the README, it's quite rudimentary for now, but better than nothing.
