### ISSUE TITLE
display-buffer-alist is not restored properly

### ISSUE THREAD

**Issue by yewton** [alexluigit/dirvish#9]
1. `dirvish-saved-display-buffer-alist` is initialized at load time so modifications to `display-buffer-alist` after that will be gone
2. Even if update `dirvish-saved-display-buffer-alist` before `dirvish-activate`,
    `dirvish-deactivate` does not always restore `display-buffer-alist` for some reason.
    As a result, `display-buffer-alist` will be updated to `dirvish-display-buffer-alist`

Possible workaround:

```emacs-lisp
(defun ad-dirvish-activate (&rest _)
  (setq dirvish-saved-display-buffer-alist display-buffer-alist))

(defun ad-dirvish-deactivate (&rest _)
  (setq display-buffer-alist dirvish-saved-display-buffer-alist))

(advice-add 'dirvish-activate :before #'ad-dirvish-activate)
(advice-add 'dirvish-deactivate :before #'ad-dirvish-deactivate)
```

**Comment by alexluigit** [comment]
Did https://github.com/alexluigit/dirvish/commit/17c434783ff8eb4e3546ec731284717391a1cad1 fixed this for you?

> 1. `dirvish-saved-display-buffer-alist` is initialized at load time so modifications to `display-buffer-alist` after that will be gone

Current solution for restoring `display-buffer-alist` do not track the run-time modifications on this variable, maybe this should be improved. Can you elaborate more about your use cases, like why would you set this variable multiple times in your config?

**Comment by yewton** [comment]
Thank you for taking you time!

I have confirmed that the restoration does not work in the following cases:

1. The dirvish window's buffer has changed within the same window ( with `previous-buffer` or `switch-to-buffer` etc. )
2. The dirvish window has been closed ( with `delete-window` etc. )

If I added `dirvish-rebuild-parents-h` to `window-buffer-change-functions` *globally* , then everything seems work correctly.

> Can you elaborate more about your use cases, like why would you set this variable multiple times in your config?

I don't set `display-buffer-alist` multiple times but I have set it after dirvish loaded
( More precisely, I have set it in `emacs-startup-hook` ).
It is just a matter of loading/declaration order.
I could avoid the issue by adjusting my init scripts for the time being, but I would be happy if Dirvish honored the run-time value.

**Comment by yewton** [comment]
> If I added dirvish-rebuild-parents-h to window-buffer-change-functions globally , then everything seems work correctly.

I'm sorry, this isn't work well with `(dirvish-peek-mode 1)`...

**Comment by alexluigit** [comment]
Thanks for your feedback.

> I have confirmed that the restoration does not work in the following cases:
> 
> 1. The dirvish window's buffer has changed within the same window ( with `previous-buffer` or `switch-to-buffer` etc. )
> 2. The dirvish window has been closed ( with `delete-window` etc. )

This is actually expected behavior although seems unreasonable. The reason for the incorrect restoration is that for now dirvish ONLY deactivate a session when the command `quit-window` get invoked, all buffer switching commands like `delete-window` won't trigger the deactivation. I'll look into it and see if I can fix it.

**Comment by yewton** [comment]
I've found `display-buffer-overriding-action` in [28.13.6 The Zen of Buffer Display](https://www.gnu.org/software/emacs/manual/html_node/elisp/The-Zen-of-Buffer-Display.html)
It might be useful.

**Comment by yewton** [comment]
Oh, I was not aware of that `dirvish-display-buffer-alist` also contains the value of `display-buffer-alist`, because `display-buffer-alist` is nil when the `defconst` was called in my case.

If `dirvish-display-buffer-alist` contains original `display-buffer-alist`, I think there is no practical issue for most cases even if it is not restored properly :smile: 

I am personally using shackle.el, so I added a function to `shackle-mode-hook` that updates `dirvish-*display-buffer-alist`:

```emacs-lisp
(defun dirvish-update-display-buffer-alists ()
  (setq dirvish-display-buffer-alist
        (append '(("^\\*F\\(?:d\\|ind\\)\\*$" (display-buffer-same-window)))
                display-buffer-alist))
  (setq dirvish-saved-display-buffer-alist display-buffer-alist))

(add-hook 'shackle-mode-hook #'dirvish-update-display-buffer-alists)
```

**Comment by alexluigit** [comment]
> Oh, I was not aware of that `dirvish-display-buffer-alist` also contains the value of `display-buffer-alist`, because `display-buffer-alist` is nil when the `defconst` was called in my case.
> 
> If `dirvish-display-buffer-alist` contains original `display-buffer-alist`, I think there is no practical issue for most cases even if it is not restored properly 

Yes, you are right. The core issue is not the restoration of `display-buffer-alist`. What really matters is that `dirvish-reclaim` should be called for every window selection change, not just for the dirvish buffer itself. I believe the commit above have solved this problem.

And by the way, after some consideration, I decided to not modify the global value of `display-buffer-alist`, since the origin purpose of this hack is to solve a issue of fd-dired (https://github.com/hlissner/doom-emacs/issues/2159), seems that it might cause more issues than it solves. I've implemented an advice to solve this, and hopefully the advice can be removed in the future.

And so, I believe this hack is no longer needed!

> ```emacs-lisp
> (defun dirvish-update-display-buffer-alists ()
>   (setq dirvish-display-buffer-alist
>         (append '(("^\\*F\\(?:d\\|ind\\)\\*$" (display-buffer-same-window)))
>                 display-buffer-alist))
>   (setq dirvish-saved-display-buffer-alist display-buffer-alist))
> 
> (add-hook 'shackle-mode-hook #'dirvish-update-display-buffer-alists)
> ```

**Comment by yewton** [comment]
Thank you!
https://github.com/alexluigit/dirvish/commit/04b35dadc14ed7a05acf0213eaaa6a5a35008055 solved the issue.
