### ISSUE TITLE
[Bug] Installation on OSX with straight.el results in broken system

### ISSUE THREAD

**Issue by moogah** [alexluigit/dirvish#91]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Dirvish is broken on OSX and/or straight.el?

### Steps to reproduce

Run emacs -Q from the terminal and then M-x eval buffer 

> (defvar bootstrap-version)
> (let ((bootstrap-file
>        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
>       (bootstrap-version 5))
>   (unless (file-exists-p bootstrap-file)
>     (with-current-buffer
> 	(url-retrieve-synchronously
> 	 "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
> 	 'silent 'inhibit-cookies)
>       (goto-char (point-max))
>       (eval-print-last-sexp)))
>   (load bootstrap-file nil 'nomessage))
> 
> (setq package-enable-at-startup nil)
> 
> (straight-use-package 'use-package)
> 
> (use-package dirvish
>   :straight t)
> 
> ;; needed for OSX, though I can't say why
> (when (string= system-type "darwin")
>   (setq dired-use-ls-dired nil))
> 
> (dirvish-override-dired-mode)

### Expected behavior

M-x dirvish will bring up the 3 window view.  

Command `a` will create a new file

Instead I get the emacs warning for invoking the disabled command `dired-find-alternative-file`

### OS

MacOS

### Emacs Version

28

### Emacs Configurations

https://gist.github.com/moogah/aaae3f26bf8af3bd15a7e388eb566d4b

**Comment by alexluigit** [comment]
Will this suppress the warning and make dirvish working properly?

```emacs-lisp
(put 'dired-find-alternative-file 'disabled nil)
```

**Comment by moogah** [comment]
Unfortunately that doesn't seem to make a difference.  I will still get the warning about the disabled command.

If I press `y` when warned, then pressing `a` functions as it would in normal dired.

I'm new to emacs and _very_ new to elisp so deconstructing and debugging the code is a slow process, I appreciate your help :)

**Comment by moogah** [comment]
I don't know if this is related or maybe a separate issue, but with this config if I enter dired and choose ~/src in the minibuffer I end up with a dired buffer of ~/ instead 🤔

**Comment by alexluigit** [comment]
> Command a will create a new file ...  results in a functioning as it would in normal dired

`a` key is bound to `dired-find-alternate-file` by default, why would it create a new file?
By "as it would in normal dired" did you mean it opens a dired buffer instead a dirvish buffer?

> if I enter dired and choose ~/src in the minibuffer I end up with a dired buffer of ~/ instead

Using C-x C-f?

**Comment by moogah** [comment]
I've discovered that all the key bindings listed in the Help Menu work.. but only when the help menu is open.  Is this intended behavior?

**Comment by alexluigit** [comment]
Sorry I misunderstood you, but it seems you didn't mentioned you were pressing `a` after invoking the help menu.  You have to know that this help menu doesn't 100% reflect the keybinding of `dired-mode`.

**Comment by moogah** [comment]
Yes, I misunderstood what bindings were provided with the basic install and config, I think we can close this issue now with that understanding.

I would suggest some changes to the Help page so that future users don't make the same assumption I did though.  Maybe I can hack my way through the lisp code enough to make a PR for this..

**Comment by alexluigit** [comment]
You can, for example, map `a` to `dired-create-empty-file` in `dired-mode` so that the keybindings are consistent between help menu and actual keymap.

```emacs-lisp
(define-key dired-mode-map (kbd "a") 'dired-create-empty-file)
```

By pressing C-h f dirvish-dispatch RET you should able to see all the keys and functions in the help menu.

**Comment by moogah** [comment]
thank you, this is the concept and syntax I was looking for to understand how to customize my key bindings :)
