### ISSUE TITLE
[Feature Request] Improve GNU ls detection in dirvish-fd.el

### ISSUE THREAD

**Issue by gcv** [alexluigit/dirvish#92]
Right now, `dirvish-fd-ls-program` checks if Darwin platforms have `gls` installed. This is too Homebrew-specific. Nix installs GNU `ls` as `ls`, for example. The right approach is to check if the discovered `ls` binary is GNU. An easy way is something along the lines of:

```elisp
(let ((gnu-ls? (= 0 (shell-command (concat ls-binary " --version")))))
  ...)
```

Heuristic: non-GNU ls implementations typically don't support GNU-style long options.

**Comment by alexluigit** [comment]
Thanks for this. Close with 4a6576eb4e707067f533d7480d2eb7a2de4014e0. Feel free to reopen or send over a PR if you have better solution.
