### ISSUE TITLE
[Bug] Mode line does not refresh in dired buffers

### ISSUE THREAD

**Issue by gcv** [alexluigit/dirvish#93]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

With `dirvish-override-dired-mode` turned on, and a dired buffer opened (`M-x dired`), the Dirvish mode line does not update after `dired-next-line` or `dired-previous-line`. It updates when forced using `g` (`revert-buffer`). The mode line updating does work as expected when full-screen dirvish is on (`M-x dirvish`), so the problem seems to be isolated.

### Steps to reproduce

```
(dirvish-override-dired-mode 1)
```
`M-x dired` and navigate through a listing. The mode line does not update to show selected file information.

### Expected behavior

 The mode line should update to show selected file information.

### OS

MacOS

### Emacs Version

27

**Comment by alexluigit** [comment]
Please let me know if 6cad59fd9581eb8e26ca0ceff38a521184518676 fixed this, thanks.

**Comment by gcv** [comment]
Fixed! Thank you.

**Comment by gcv** [comment]
Actually, sorry! The problem was fixed for Emacs 27, but I just tried Dirvish with Emacs 28, and it persists. Looks like the force-mode-line-update call has to happen for 28 also.

In addition, with Emacs 28 using `revert-buffer` (<kbd>g</kbd>) causes the minibuffer to print `Window system frame should be used` (using terminal mode Emacs here).

**Comment by alexluigit** [comment]
> Looks like the force-mode-line-update call has to happen for 28 also

Thanks, fixed.

> revert-buffer (g) causes the minibuffer to print Window system frame should be used (using terminal mode Emacs here)

I've fixed this one, and here are 2 known issues you might run into when using dirvish on terminal: 
1. file-size attribute causes line skipping (using dired-next-line), seems has something to do with the `:alight-to` display property. I'll try to fix it, although for now I have no idea on how to remove that "$" sign at window fringe on terminal.
2. Preview methods that requires GUI won't work, I'll fix those `Window system frame should be used` warnings when focusing on media files, but the preview functionalities are only available on GUI.

**Comment by gcv** [comment]
Looks really good. Thank you.

Is there a good way to fully disable previews and caching for media files? I tried setting `dirvish-preview-dispatchers` to just `'(archive)`, but it tried opening images as text and copied the images into the Dirvish cache directory. Enumerating extensions in `dirvish-preview-disabled-exts` doesn't seem like a good approach.

**Comment by alexluigit** [comment]
> it tried opening images as text and copied the images into the Dirvish cache directory

You can try this: 

```emacs-lisp
(customize-set-variable 'dirvish-media-auto-cache-threshold '(0))

(defconst preview-disabled-extensions
  (append dirvish-image-exts dirvish-video-exts
          dirvish-audio-exts '("pdf" "epub" "gif")))

(dirvish-define-preview no-media (ext)
  "Disable preview for media files."
  (when (member ext preview-disabled-extensions)
    '(info . "Preview disabled for media files")))

(setq dirvish-preview-dispatchers '(archive no-media))
```

**Comment by gcv** [comment]
Excellent, thank you!
