### ISSUE TITLE
Remove or flatten modeline appearance in headerline?

### ISSUE THREAD

**Issue by tdstoff** [alexluigit/dirvish#96]
Is there an easy way to simply show the file path on the top of the buffer without a modeline appearance? I'm loving Dirvish (thank you and great job all contributors!), but can't get myself used to how busy/distracting the headerline looks compared to the classic dired setup with `hide-details-mode` turned on. This is especially apparent when multiple windows are open which is common with `dired-dwim-target` on.

**Comment by alexluigit** [comment]
After 0317384f2e8a8643ae61b450a4e6d0d2d32cd06c I believe you can achieve this by setting `dirvish-header-line-position` to `disable`.

**Comment by tdstoff** [comment]
Nice, that worked.

Any suggestions on how to still show the file path after that so the user knows where they are? I am still partial to the default behavior where it's just shown in text on top, but the main idea I was after is to just have a single modeline per buffer instead of two.

**Comment by alexluigit** [comment]
So you still want the header line, but want the path showing there be more quite (do not update itself all the time)?

**Comment by tdstoff** [comment]
Hi @alexluigit, yes, I was missing that latest commit. The current `'disable` setting is what I was after. Your default headerline setting is cool, but I couldn't get over being distracted by it, so I'll use this for now. Thanks!
