### ISSUE TITLE
Files including `%b` get expanded to `<username>`

### ISSUE THREAD

**Issue by jdtsmith** [alexluigit/dirvish#97]
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Files ending in `%b`, such as backup files, have their names expanded to include `<user>` in place of the tilde in the top mode line.  E.g. `%backup%~` becomes `.emacs.d<myuser>ackup`. 

### Steps to reproduce

Create a file named `%backup%~` and browse to it.  Notice the top modeline has included the directory name and replaces `%b` with it and the user name in angle brackets. 

### Expected behavior

File name shown as is. 

### OS

MacOS

### Emacs Version

28

**Comment by alexluigit** [comment]
Fixed at 2eac029a19d614cac7cdf5f223dd156a2e9e36af
